In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Load the Dataset

In [7]:
df = pd.read_csv("../data/sales_data.csv")

Check the First Rows

In [8]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Product,Category,Quantity,Unit_Price,Cost_Price,Discount,City,State,Region,Salesperson,Payment_Mode
0,ORD3526,2026-03-04,C0223,Sneha Mishra,Office Chair,Furniture,2.0,12000.0,8500,10,Gorakhpur,Uttar Pradesh,North,Sneha,UPI
1,ORD3923,2026-03-01,C0212,Karan Agarwal,Notebook,Stationery,1.0,120.0,65,10,Delhi,Delhi,North,Priya,Debit Card
2,ORD1890,2026-06-24,C0015,Rahul Yadav,Smartphone,Electronics,1.0,28000.0,22000,0,Delhi,Delhi,North,Neha,UPI
3,ORD1658,2026-08-02,C0467,Kavita Singh,Notebook,Stationery,5.0,120.0,65,10,Kolkata,West Bengal,East,Neha,Net Banking
4,ORD5317,2026-02-06,C0979,Ravi Sharma,Office Chair,Furniture,4.0,12000.0,8500,20,Jaipur,Rajasthan,north,Karan,Net Banking

Check Dataset Size

In [10]:
df.shape

(5030, 15)

See Columns Names

In [15]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Product',
       'Category', 'Quantity', 'Unit_Price', 'Cost_Price', 'Discount', 'City',
       'State', 'Region', 'Salesperson', 'Payment_Mode'],
      dtype='str')

Data information

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5030 entries, 0 to 5029
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       5030 non-null   str
 1   Order_Date     5030 non-null   str
 2   Customer_ID    5030 non-null   str
 3   Customer_Name  4952 non-null   str
 4   Product        5030 non-null   str
 5   Category       5030 non-null   str
 6   Quantity       4985 non-null   float64
 7   Unit_Price     5005 non-null   str
 8   Cost_Price     5030 non-null   int64
 9   Discount       5030 non-null   int64
 10  City           4995 non-null   str
 11  State          5030 non-null   str
 12  Region         5030 non-null   str
 13  Salesperson    5030 non-null   str
 14  Payment_Mode   5000 non-null   str
dtypes: float64(1), int64(2), str(12)
memory usage: 589.6 KB

Find Missing Values

In [16]:
df.isna().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name    78
Product           0
Category          0
Quantity         45
Unit_Price       25
Cost_Price        0
Discount          0
City             35
State             0
Region            0
Salesperson       0
Payment_Mode     30
dtype: int64

Find Duplicatt Values

In [20]:
df.duplicated().sum()

np.int64(30)

Investigate Missing Customer Names

In [22]:
df[df["Customer_Name"].isna()]

,Order_ID,Order_Date,Customer_ID,Customer_Name,Product,Category,Quantity,Unit_Price,Cost_Price,Discount,City,State,Region,Salesperson,Payment_Mode
24,ORD3173,2026-06-04,C0851,NaN,Notebook,Stationery,5.0,120.0,65,15,Jaipur,Rajasthan,North,Ravi,UPI
387,ORD3489,2026-05-21,C0784,NaN,Printer,Electronics,5.0,16000.0,12500,10,Gorakhpur,Uttar Pradesh,North,Ravi,Debit Card
422,ORD4985,2026-02-09,C0827,NaN,Pen Set,Stationery,4.0,250.0,140,20,Bhubaneswar,Odisha,East,Sneha,UPI
447,ORD4152,2026-02-16,C0680,NaN,Smartphone,Electronics,1.0,28000.0,22000,20,Bhubaneswar,Odisha,East,Sneha,Debit Card
538,ORD5440,2026-05-29,C0992,NaN,Notebook,Stationery,6.0,120.0,65,10,Lucknow,Uttar Pradesh,North,Neha,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4747,ORD2061,2026-01-17,C0193,NaN,Pen Set,Stationery,3.0,250.0,140,0,Ahmedabad,Gujarat,West,Ravi,Net Banking
4768,ORD2046,2026-07-02,C0216,NaN,Laptop,Electronics,4.0,55000.0,45000,20,Bengaluru,Karnataka,South,Sneha,UPI
4819,ORD1263,2026-03-01,C0693,NaN,laptop,Electronics,5.0,16000.0,12500,20,Lucknow,Uttar Pradesh,North,Amit,Net Banking
4888,ORD3676,2026-07-30,C0946,NaN,Monitor,Electronics,5.0,18000.0,14000,0,Bengaluru,Karnataka,South,Priya,Debit Card
4962,ORD5912,2026-01-17,C0736,NaN,Pen Set,Stationery,5.0,250.0,140,20,Lucknow,Uttar Pradesh,North,Neha,Credit Card

Load the Customer Master

In [23]:
customer_master = pd.read_csv("../data/customer_master_final.csv")

Look at the Master

In [24]:
customer_master.head()

  Customer_ID Customer_Name
0       C0001   Priya Gupta
1       C0002   Amit Saxena
2       C0003   Nisha Gupta
3       C0004   Neha Tiwari
4       C0005  Priya Mishra

Check Master Size

In [25]:
customer_master.shape

(1000, 2)

In [27]:
customer_master.columns

Index(['Customer_ID', 'Customer_Name'], dtype='str')

Data Types

In [26]:
customer_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    1000 non-null   str
 1   Customer_Name  1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

Now Test Our Hypothesis

Extracting the IDs from the missing-name records

In [42]:
missing_customer_ids = df.loc[
    df["Customer_Name"].isnull(),
    "Customer_ID"
]
missing_customer_ids.value_counts().sum()

np.int64(78)

Check Whether Those IDs Exist in the Master

In [44]:
missing_customer_ids.isin(customer_master["Customer_ID"]).value_counts()

Customer_ID
True    78
Name: count, dtype: int64

Let's See the Correct Names

In [45]:
customer_master[
    customer_master["Customer_ID"].isin(missing_customer_ids)
]

    Customer_ID Customer_Name
25        C0026  Kavita Verma
39        C0040   Karan Yadav
54        C0055  Kavita Kumar
59        C0060  Manish Verma
99        C0100   Rahul Kumar
..          ...           ...
945       C0946   Amit Sharma
960       C0961    Neha Verma
974       C0975  Amit Agarwal
978       C0979   Ravi Sharma
991       C0992   Karan Gupta

[78 rows x 2 columns]

Compare Sales Data With Customer Master

In [51]:
missing_customers = df.loc[
    df["Customer_Name"].isnull(),
    ["Order_ID", "Customer_ID", "Customer_Name"]
].merge(
    customer_master,
    on="Customer_ID",
    how="left"
)

In [50]:
missing_customers.head(10)

  Order_ID Customer_ID Customer_Name_x Customer_Name_y
0  ORD3173       C0851             NaN      Neha Mehta
1  ORD3489       C0784             NaN     Meera Gupta
2  ORD4985       C0827             NaN     Varun Gupta
3  ORD4152       C0680             NaN     Arjun Yadav
4  ORD5440       C0992             NaN     Karan Gupta
5  ORD1234       C0961             NaN      Neha Verma
6  ORD3971       C0117             NaN     Sneha Singh
7  ORD1803       C0662             NaN  Manish Agarwal
8  ORD3211       C0398             NaN   Simran Sharma
9  ORD4287       C0526             NaN     Pooja Kumar

In [52]:
missing_customers["Customer_Name_y"].isnull().sum()

np.int64(0)

In [53]:
missing_customers["Customer_Name_y"].isnull().sum()

np.int64(0)

Create a simple lookup

In [55]:
name_map = customer_master.set_index("Customer_ID")["Customer_Name"]
name_map

Customer_ID
C0001       Priya Gupta
C0002       Amit Saxena
C0003       Nisha Gupta
C0004       Neha Tiwari
C0005      Priya Mishra
              ...
C0996    Simran Chauhan
C0997      Simran Yadav
C0998      Karan Tiwari
C0999      Shreya Yadav
C1000     Meera Chauhan
Name: Customer_Name, Length: 1000, dtype: str

Fill the missing names

In [56]:
df["Customer_Name"] = df["Customer_Name"].fillna(
    df["Customer_ID"].map(name_map)
)

Validating Our Cleaning

In [58]:
df["Customer_Name"].isnull().sum()

np.int64(0)

Look at the Missing Quantities

In [ ]:
df[df["Quantity"].isnull()]

NameError: name 'x' is not defined

Investigate Missing Quantity

In [66]:
df[df["Quantity"].isnull()][
    ["Order_ID", "Product", "Category", "Unit_Price", "Cost_Price"]
]

     Order_ID       Product     Category Unit_Price  Cost_Price
100   ORD1298          Desk    Furniture     9000.0        6200
163   ORD4500          Desk    Furniture     9000.0        6200
391   ORD5710       Monitor  Electronics    18000.0       14000
456   ORD1388       Monitor  Electronics    18000.0       14000
461   ORD5465          Desk    Furniture     9000.0        6200
469   ORD4025       Printer  Electronics    16000.0       12500
489   ORD3933       Printer  Electronics    16000.0       12500
552   ORD4154       Pen Set   Stationery      250.0         140
714   ORD4047    Headphones  Electronics     3500.0        2200
725   ORD1121          Desk    Furniture     9000.0        6200
819   ORD1379      Notebook   Stationery      120.0          65
884   ORD3742    Headphones  Electronics     3500.0        2200
942   ORD3154       Printer  Electronics    16000.0       12500
949   ORD5295  Office Chair    Furniture    12000.0        8500
1182  ORD5555        Laptop  Electronics    55000.0       45000
1354  ORD4076    Smartphone  Electronics    28000.0       22000
1376  ORD1565          Desk    Furniture     9000.0        6200
1448  ORD2107    Smartphone  Electronics    28000.0       22000
1553  ORD1802  Office Chair    Furniture    12000.0        8500
1597  ORD1480  Office Chair    Furniture    12000.0        8500
1672  ORD3857  Office Chair    Furniture    12000.0        8500
1945  ORD2813          Desk    Furniture     9000.0        6200
1976  ORD4204          Desk    Furniture     9000.0        6200
2047  ORD2455       Monitor  Electronics    18000.0       14000
2124  ORD3020      Keyboard  Electronics     1800.0        1100
2159  ORD5868    Smartphone  Electronics    28000.0       22000
2249  ORD2728       Monitor  Electronics    18000.0       14000
2272  ORD5324    Headphones  Electronics     3500.0        2200
2288  ORD2106  Office Chair    Furniture    12000.0        8500
2634  ORD5826       Monitor  Electronics    18000.0       14000
2651  ORD3660  Office Chair    Furniture    12000.0        8500
2680  ORD2353          Desk    Furniture     9000.0        6200
3025  ORD5455       Printer  Electronics    16000.0       12500
3279  ORD4145      Keyboard  Electronics     1800.0        1100
3301  ORD5037    Headphones  Electronics     3500.0        2200
3337  ORD5743      Notebook   Stationery      120.0          65
3393  ORD1793    Smartphone  Electronics    28000.0       22000
3499  ORD2691       Printer  Electronics    16000.0       12500
3511  ORD5415  Office Chair    Furniture    12000.0        8500
3672  ORD1432        Laptop  Electronics    55000.0       45000
3699  ORD3033        Laptop  Electronics    55000.0       45000
3755  ORD3420  Office Chair    Furniture    12000.0        8500
4161  ORD4326       Pen Set   Stationery      250.0         140
4369  ORD5880      Notebook   Stationery      120.0          65
4881  ORD1664      Keyboard  Electronics     1800.0        1100

In [67]:
df["Quantity"].describe()

count    4985.000000
mean        5.597392
std        39.882806
min        -3.000000
25%         2.000000
50%         4.000000
75%         6.000000
max       999.000000
Name: Quantity, dtype: float64

In [68]:
df["Quantity"].value_counts().sort_index()

Quantity
-3.0       11
 1.0      708
 2.0      671
 3.0      717
 4.0      740
 5.0      707
 6.0      713
 7.0      710
 999.0      8
Name: count, dtype: int64

Create a Missing-Quantity Flag

In [69]:
df["Quantity_Missing"] = df["Quantity"].isnull()

In [70]:
df["Quantity_Missing"].value_counts()

Quantity_Missing
False    4985
True       45
Name: count, dtype: int64

Now Investigate Invalid Quantities

In [71]:
df[df["Quantity"] <= 0][["Order_ID", "Product", "Quantity"]]

     Order_ID       Product  Quantity
644   ORD5622      Keyboard      -3.0
1104  ORD1844  Office Chair      -3.0
1184  ORD2967        Laptop      -3.0
1460  ORD5123      Keyboard      -3.0
1792  ORD2217          Desk      -3.0
1856  ORD5086  Office Chair      -3.0
1967  ORD1555    Smartphone      -3.0
2399  ORD1998        Laptop      -3.0
3573  ORD1038       Pen Set      -3.0
3879  ORD2846       Printer      -3.0
4430  ORD5519        Laptop      -3.0

In [72]:
df[df["Quantity"] > 10][["Order_ID", "Product", "Quantity"]]

     Order_ID     Product  Quantity
1446  ORD3265      Laptop     999.0
1805  ORD2872        Desk     999.0
2259  ORD4859    Notebook     999.0
2778  ORD2767  Smartphone     999.0
3063  ORD4429     Printer     999.0
3321  ORD3937    Notebook     999.0
3351  ORD3549     Pen Set     999.0
4445  ORD2839        Desk     999.0

In [73]:
print("Missing:", df["Quantity"].isnull().sum())
print("Negative:", (df["Quantity"] < 0).sum())
print("999:", (df["Quantity"] == 999).sum())

Missing: 45
Negative: 11
999: 8

Missing Unit_Price

In [77]:
df[df["Unit_Price"].isnull()][
    ["Order_ID", "Product", "Category", "Quantity", "Cost_Price"]
]

     Order_ID       Product       Category  Quantity  Cost_Price
182   ORD2269          Desk      Furniture       1.0        6200
529   ORD5841          Desk   Electronics        1.0        6200
708   ORD3331  Office Chair      Furniture       2.0        8500
934   ORD1669      Notebook     Stationery       3.0          65
969   ORD1880       Pen Set     Stationery       1.0         140
1047  ORD5947       Monitor    Electronics       6.0       14000
1193  ORD5240        Laptop    Electronics       6.0       45000
1219  ORD3221  Office Chair      Furniture       5.0        8500
1311  ORD4182    Smartphone    Electronics       1.0       22000
1689  ORD5771    Smartphone    Electronics       5.0       22000
1898  ORD3706      Keyboard    Electronics       2.0        1100
2095  ORD1980    Headphones    Electronics       4.0        2200
2162  ORD1986  Office Chair      Furniture       2.0        8500
2274  ORD3332        Laptop    Electronics       5.0       45000
2371  ORD5293  Office Chair      Furniture       1.0        8500
2471  ORD3461       Monitor    Electronics       4.0       14000
2689  ORD5341    Smartphone    Electronics       3.0       22000
2876  ORD4796       Monitor    Electronics       1.0       14000
3220  ORD1353       Printer    Electronics       1.0       12500
3464  ORD4806          Desk      Furniture       3.0        6200
3512  ORD4509       Pen Set    ELECTRONICS       4.0         140
3950  ORD3762      Keyboard    Electronics       1.0        1100
4078  ORD3718       Pen Set     Stationery       7.0         140
4378  ORD5165       Printer    Electronics       4.0       12500
4554  ORD1718    Smartphone    Electronics       3.0       22000

In [78]:
df["Unit_Price"].value_counts().head(10)

Unit_Price
55000.0    528
3500.0     525
12000.0    519
120.0      516
1800.0     503
18000.0    497
250.0      488
28000.0    480
9000.0     470
16000.0    469
Name: count, dtype: int64

In [80]:
df.groupby("Product")["Unit_Price"].unique()

Product
 LAPTOP         [12000.0, 9000.0, 55000.0, 3500.0, 18000.0, 25...
 Laptop         [1800.0, 16000.0, 28000.0, 55000.0, 3500.0, 18...
Desk                                                [9000.0, nan]
Headphones                                          [3500.0, nan]
Keyboard                                   [1800.0, nan, ₹55,000]
Laptop                                    [55000.0, nan, ₹55,000]
Laptop                          [120.0, 16000.0, 3500.0, 55000.0]
Monitor                                            [18000.0, nan]
Notebook                                    [120.0, nan, ₹55,000]
Office Chair                              [12000.0, nan, ₹55,000]
Pen Set                                     [250.0, ₹55,000, nan]
Printer                                   [16000.0, ₹55,000, nan]
Smartphone                                [28000.0, nan, ₹55,000]
laptop          [1800.0, 3500.0, 9000.0, 28000.0, 16000.0, 120...
Name: Unit_Price, dtype: object

CURRENCY DISCREPANCIES

In [81]:
df[df["Unit_Price"].astype(str).str.contains("₹", na=False)][
    ["Order_ID", "Product", "Unit_Price"]
]

     Order_ID       Product Unit_Price
401   ORD3303       Pen Set    ₹55,000
1054  ORD2748      Notebook    ₹55,000
1215  ORD4440       Printer    ₹55,000
1879  ORD3079  Office Chair    ₹55,000
2167  ORD1982      Notebook    ₹55,000
2598  ORD4927        Laptop    ₹55,000
2798  ORD3103       Printer    ₹55,000
3743  ORD3668      Keyboard    ₹55,000
4645  ORD5754    Smartphone    ₹55,000
4649  ORD4507      Keyboard    ₹55,000

In [82]:
df[df["Unit_Price"].isnull()][
    ["Product", "Cost_Price"]
].value_counts()

Product       Cost_Price
Office Chair  8500          4
Smartphone    22000         4
Desk          6200          3
Pen Set       140           3
Monitor       14000         3
Laptop        45000         2
Keyboard      1100          2
Printer       12500         2
Notebook      65            1
Headphones    2200          1
Name: count, dtype: int64

In [83]:
df.groupby("Cost_Price")["Unit_Price"].unique()

Cost_Price
65         [120.0, nan, ₹55,000]
140        [250.0, ₹55,000, nan]
1100      [1800.0, nan, ₹55,000]
2200               [3500.0, nan]
6200               [9000.0, nan]
8500     [12000.0, nan, ₹55,000]
12500    [16000.0, ₹55,000, nan]
14000             [18000.0, nan]
22000    [28000.0, nan, ₹55,000]
45000    [55000.0, nan, ₹55,000]
Name: Unit_Price, dtype: object

Create the Price Mapping

In [84]:
price_map = {
    65: 120,
    140: 250,
    1100: 1800,
    2200: 3500,
    6200: 9000,
    8500: 12000,
    12500: 16000,
    14000: 18000,
    22000: 28000,
    45000: 55000
}

Fill Only the Missing Prices

In [85]:
df["Unit_Price"] = df["Unit_Price"].fillna(
    df["Cost_Price"].map(price_map)
)

In [86]:
df["Unit_Price"].isnull().sum()

np.int64(0)

Missing City

In [87]:
df[df["City"].isnull()][
    ["Order_ID", "Customer_ID", "Customer_Name", "State", "Region"]
]

     Order_ID Customer_ID   Customer_Name          State Region
77    ORD1857       C0128    Aditya Verma  Uttar Pradesh  North
302   ORD4654       C0277    Rohan Tiwari    West Bengal   East
585   ORD2127       C0151    Priya Mishra      Telangana  South
820   ORD2188       C0188     Ravi Tiwari         Odisha   East
1136  ORD1112       C0300   Anjali Saxena    Maharashtra   West
1138  ORD1221       C0055    Kavita Kumar     Tamil Nadu  South
1203  ORD2739       C0976    Arjun Sharma      Telangana  South
1266  ORD5461       C0002     Amit Saxena  Uttar Pradesh  North
1554  ORD2289       C0246    Rohan Tiwari    Maharashtra   West
1609  ORD4138       C0879     Pooja Gupta    Maharashtra   West
1755  ORD4718       C0449   Varun Chauhan         Odisha   East
1833  ORD5990       C0879     Pooja Gupta  Uttar Pradesh  North
1937  ORD4555       C0053     Pooja Patel      Telangana  South
1973  ORD3400       C0945    Vikas Mishra      Karnataka  South
2238  ORD2750       C0128    Aditya Verma    West Bengal   East
2283  ORD1853       C0808     Rohan Kumar  Uttar Pradesh  North
2302  ORD3374       C0024     Pooja Yadav          Delhi  North
2392  ORD5218       C0342   Shreya Saxena    Maharashtra   West
2450  ORD2755       C0744    Varun Mishra      Telangana  South
2524  ORD1783       C0118     Meera Yadav        Gujarat   West
2745  ORD1594       C0593     Arjun Verma      Telangana  South
2987  ORD3133       C0808     Rohan Kumar    Maharashtra   West
3161  ORD5538       C0899    Kavita Joshi    Maharashtra   West
3472  ORD2220       C0275   Nisha Agarwal  Uttar Pradesh  North
3705  ORD5630       C0916     Meera Patel        Gujarat   West
3864  ORD5061       C0750     Nisha Joshi     Tamil Nadu  South
4310  ORD3159       C0079    Amit Chauhan      Rajasthan  North
4365  ORD1281       C0867  Anjali Agarwal          Delhi  North
4402  ORD2849       C0829    Sneha Saxena  Uttar Pradesh  North
4420  ORD3049       C0137     Nisha Yadav      Telangana  South
4454  ORD5137       C0535     Varun Kumar    West Bengal   East
4615  ORD4747       C0676    Ravi Agarwal    Maharashtra   West
4648  ORD3745       C0671    Meera Saxena  Uttar Pradesh  North
4789  ORD5434       C0236    Simran Gupta         Odisha   East
4909  ORD5637       C0790    Pooja Sharma      Telangana  South

Check State and Region

In [88]:
df[df["City"].isnull()]["State"].value_counts()

State
Uttar Pradesh    7
Telangana        7
Maharashtra      7
West Bengal      3
Odisha           3
Tamil Nadu       2
Delhi            2
Gujarat          2
Karnataka        1
Rajasthan        1
Name: count, dtype: int64

In [89]:
df[df["City"].isnull()]["Region"].value_counts()

Region
North    10
South    10
West      9
East      6
Name: count, dtype: int64

Check Customer Consistency

In [90]:
df[df["City"].isnull()]["Customer_ID"].isin(
    df[df["City"].notnull()]["Customer_ID"]
).value_counts()

Customer_ID
True    35
Name: count, dtype: int64

Look at the Customers With Missing Cities

In [91]:
df[df["City"].isnull()][
    ["Customer_ID", "Customer_Name", "State"]
]

     Customer_ID   Customer_Name          State
77         C0128    Aditya Verma  Uttar Pradesh
302        C0277    Rohan Tiwari    West Bengal
585        C0151    Priya Mishra      Telangana
820        C0188     Ravi Tiwari         Odisha
1136       C0300   Anjali Saxena    Maharashtra
1138       C0055    Kavita Kumar     Tamil Nadu
1203       C0976    Arjun Sharma      Telangana
1266       C0002     Amit Saxena  Uttar Pradesh
1554       C0246    Rohan Tiwari    Maharashtra
1609       C0879     Pooja Gupta    Maharashtra
1755       C0449   Varun Chauhan         Odisha
1833       C0879     Pooja Gupta  Uttar Pradesh
1937       C0053     Pooja Patel      Telangana
1973       C0945    Vikas Mishra      Karnataka
2238       C0128    Aditya Verma    West Bengal
2283       C0808     Rohan Kumar  Uttar Pradesh
2302       C0024     Pooja Yadav          Delhi
2392       C0342   Shreya Saxena    Maharashtra
2450       C0744    Varun Mishra      Telangana
2524       C0118     Meera Yadav        Gujarat
2745       C0593     Arjun Verma      Telangana
2987       C0808     Rohan Kumar    Maharashtra
3161       C0899    Kavita Joshi    Maharashtra
3472       C0275   Nisha Agarwal  Uttar Pradesh
3705       C0916     Meera Patel        Gujarat
3864       C0750     Nisha Joshi     Tamil Nadu
4310       C0079    Amit Chauhan      Rajasthan
4365       C0867  Anjali Agarwal          Delhi
4402       C0829    Sneha Saxena  Uttar Pradesh
4420       C0137     Nisha Yadav      Telangana
4454       C0535     Varun Kumar    West Bengal
4615       C0676    Ravi Agarwal    Maharashtra
4648       C0671    Meera Saxena  Uttar Pradesh
4789       C0236    Simran Gupta         Odisha
4909       C0790    Pooja Sharma      Telangana

In [92]:
df[df["Customer_ID"].isin(
    df[df["City"].isnull()]["Customer_ID"]
)][
    ["Customer_ID", "Customer_Name", "City", "State"]
].sort_values("Customer_ID")

     Customer_ID Customer_Name     City          State
3538       C0002   Amit Saxena  Kolkata    West Bengal
1865       C0002   Amit Saxena     Pune    Maharashtra
4416       C0002   Amit Saxena    Delhi          Delhi
1266       C0002   Amit Saxena      NaN  Uttar Pradesh
884        C0002   Amit Saxena   Mumbai    Maharashtra
...          ...           ...      ...            ...
1203       C0976  Arjun Sharma      NaN      Telangana
1147       C0976  Arjun Sharma  Chennai     Tamil Nadu
2681       C0976  Arjun Sharma     Pune    Maharashtra
5011       C0976  Arjun Sharma     Pune    Maharashtra
4782       C0976  Arjun Sharma  Kolkata    West Bengal

[205 rows x 4 columns]

Check Whether Customers Have One Consistent City

In [93]:
city_check = df[df["City"].notnull()].groupby("Customer_ID")["City"].nunique()

In [94]:
missing_city_customers = df[df["City"].isnull()]["Customer_ID"].unique()

In [95]:
city_check.loc[city_check.index.isin(missing_city_customers)].value_counts()

City
3    10
4     8
6     5
2     4
7     2
5     2
8     1
Name: count, dtype: int64

Check the Actual City Mapping

In [96]:
city_map = df[df["City"].notnull()].groupby("Customer_ID")["City"].first()

In [97]:
df.loc[
    df["City"].isnull(),
    ["Customer_ID", "State"]
].assign(
    Known_City=lambda x: x["Customer_ID"].map(city_map)
)

     Customer_ID          State   Known_City
77         C0128  Uttar Pradesh       Jaipur
302        C0277    West Bengal         Pune
585        C0151      Telangana       Mumbai
820        C0188         Odisha  Bhubaneswar
1136       C0300    Maharashtra       Jaipur
1138       C0055     Tamil Nadu      Chennai
1203       C0976      Telangana         Pune
1266       C0002  Uttar Pradesh       Mumbai
1554       C0246    Maharashtra    Bengaluru
1609       C0879    Maharashtra       Jaipur
1755       C0449         Odisha  Bhubaneswar
1833       C0879  Uttar Pradesh       Jaipur
1937       C0053      Telangana      Kolkata
1973       C0945      Karnataka         Pune
2238       C0128    West Bengal       Jaipur
2283       C0808  Uttar Pradesh    Bengaluru
2302       C0024          Delhi    Ahmedabad
2392       C0342    Maharashtra  Bhubaneswar
2450       C0744      Telangana       Mumbai
2524       C0118        Gujarat       Jaipur
2745       C0593      Telangana        Delhi
2987       C0808    Maharashtra    Bengaluru
3161       C0899    Maharashtra  Bhubaneswar
3472       C0275  Uttar Pradesh    Bengaluru
3705       C0916        Gujarat       Mumbai
3864       C0750     Tamil Nadu         Pune
4310       C0079      Rajasthan    Bengaluru
4365       C0867          Delhi       Jaipur
4402       C0829  Uttar Pradesh        Delhi
4420       C0137      Telangana    Gorakhpur
4454       C0535    West Bengal    Hyderabad
4615       C0676    Maharashtra      Lucknow
4648       C0671  Uttar Pradesh    Hyderabad
4789       C0236         Odisha      Lucknow
4909       C0790      Telangana    Hyderabad

In [98]:
df.loc[
    df["City"].isnull(),
    "Customer_ID"
].map(city_map).isnull().sum()

np.int64(0)

Check the City Result

In [99]:
city_check = df[df["City"].notnull()].groupby("Customer_ID")["City"].nunique()

missing_city_customers = df[df["City"].isnull()]["Customer_ID"].unique()

city_check.loc[city_check.index.isin(missing_city_customers)].value_counts()

City
3    10
4     8
6     5
2     4
7     2
5     2
8     1
Name: count, dtype: int64

Create the City Map

In [100]:
city_map = df[df["City"].notnull()].groupby("Customer_ID")["City"].first()

In [101]:
df.loc[
    df["City"].isnull(),
    ["Customer_ID", "State"]
].assign(
    City_From_Other_Orders=lambda x: x["Customer_ID"].map(city_map)
)

     Customer_ID          State City_From_Other_Orders
77         C0128  Uttar Pradesh                 Jaipur
302        C0277    West Bengal                   Pune
585        C0151      Telangana                 Mumbai
820        C0188         Odisha            Bhubaneswar
1136       C0300    Maharashtra                 Jaipur
1138       C0055     Tamil Nadu                Chennai
1203       C0976      Telangana                   Pune
1266       C0002  Uttar Pradesh                 Mumbai
1554       C0246    Maharashtra              Bengaluru
1609       C0879    Maharashtra                 Jaipur
1755       C0449         Odisha            Bhubaneswar
1833       C0879  Uttar Pradesh                 Jaipur
1937       C0053      Telangana                Kolkata
1973       C0945      Karnataka                   Pune
2238       C0128    West Bengal                 Jaipur
2283       C0808  Uttar Pradesh              Bengaluru
2302       C0024          Delhi              Ahmedabad
2392       C0342    Maharashtra            Bhubaneswar
2450       C0744      Telangana                 Mumbai
2524       C0118        Gujarat                 Jaipur
2745       C0593      Telangana                  Delhi
2987       C0808    Maharashtra              Bengaluru
3161       C0899    Maharashtra            Bhubaneswar
3472       C0275  Uttar Pradesh              Bengaluru
3705       C0916        Gujarat                 Mumbai
3864       C0750     Tamil Nadu                   Pune
4310       C0079      Rajasthan              Bengaluru
4365       C0867          Delhi                 Jaipur
4402       C0829  Uttar Pradesh                  Delhi
4420       C0137      Telangana              Gorakhpur
4454       C0535    West Bengal              Hyderabad
4615       C0676    Maharashtra                Lucknow
4648       C0671  Uttar Pradesh              Hyderabad
4789       C0236         Odisha                Lucknow
4909       C0790      Telangana              Hyderabad

Check for Missing Mappings

In [102]:
df.loc[
    df["City"].isnull(),
    "Customer_ID"
].map(city_map).isnull().sum()

np.int64(0)

Now Check State Consistency

In [103]:
df.loc[
    df["City"].isnull(),
    ["Customer_ID", "State"]
].assign(
    City=lambda x: x["Customer_ID"].map(city_map)
)

     Customer_ID          State         City
77         C0128  Uttar Pradesh       Jaipur
302        C0277    West Bengal         Pune
585        C0151      Telangana       Mumbai
820        C0188         Odisha  Bhubaneswar
1136       C0300    Maharashtra       Jaipur
1138       C0055     Tamil Nadu      Chennai
1203       C0976      Telangana         Pune
1266       C0002  Uttar Pradesh       Mumbai
1554       C0246    Maharashtra    Bengaluru
1609       C0879    Maharashtra       Jaipur
1755       C0449         Odisha  Bhubaneswar
1833       C0879  Uttar Pradesh       Jaipur
1937       C0053      Telangana      Kolkata
1973       C0945      Karnataka         Pune
2238       C0128    West Bengal       Jaipur
2283       C0808  Uttar Pradesh    Bengaluru
2302       C0024          Delhi    Ahmedabad
2392       C0342    Maharashtra  Bhubaneswar
2450       C0744      Telangana       Mumbai
2524       C0118        Gujarat       Jaipur
2745       C0593      Telangana        Delhi
2987       C0808    Maharashtra    Bengaluru
3161       C0899    Maharashtra  Bhubaneswar
3472       C0275  Uttar Pradesh    Bengaluru
3705       C0916        Gujarat       Mumbai
3864       C0750     Tamil Nadu         Pune
4310       C0079      Rajasthan    Bengaluru
4365       C0867          Delhi       Jaipur
4402       C0829  Uttar Pradesh        Delhi
4420       C0137      Telangana    Gorakhpur
4454       C0535    West Bengal    Hyderabad
4615       C0676    Maharashtra      Lucknow
4648       C0671  Uttar Pradesh    Hyderabad
4789       C0236         Odisha      Lucknow
4909       C0790      Telangana    Hyderabad

Fill Missing Cities

In [104]:
df["City"] = df["City"].fillna(
    df["Customer_ID"].map(city_map)
)

Validating

In [105]:
df["City"].isnull().sum()

np.int64(0)

Check Remaining Missing Values

In [106]:
df.isnull().sum()

Order_ID             0
Order_Date           0
Customer_ID          0
Customer_Name        0
Product              0
Category             0
Quantity            45
Unit_Price           0
Cost_Price           0
Discount             0
City                 0
State                0
Region               0
Salesperson          0
Payment_Mode        30
Quantity_Missing     0
dtype: int64

 Missing Column: Payment_Mode

In [107]:
df[df["Payment_Mode"].isnull()][
    ["Order_ID", "Customer_ID", "Customer_Name", "Payment_Mode"]
]

     Order_ID Customer_ID   Customer_Name Payment_Mode
110   ORD4759       C0009     Rohan Yadav          NaN
132   ORD5925       C0349     Rohan Kumar          NaN
232   ORD2630       C0899    Kavita Joshi          NaN
736   ORD3971       C0117     Sneha Singh          NaN
738   ORD1512       C0749     Priya Kumar          NaN
1065  ORD2025       C0140    Arjun Tiwari          NaN
1240  ORD3806       C0479    Anjali Verma          NaN
1406  ORD2505       C0104   Karan Agarwal          NaN
1626  ORD1499       C0619    Aditya Kumar          NaN
1754  ORD3760       C0117     Sneha Singh          NaN
1819  ORD2212       C0142    Priya Tiwari          NaN
1907  ORD2367       C0399     Varun Singh          NaN
2049  ORD5289       C0132     Meera Mehta          NaN
2210  ORD5278       C0516    Meera Tiwari          NaN
2345  ORD3588       C0030   Aditya Saxena          NaN
2556  ORD5682       C0695   Manish Tiwari          NaN
2564  ORD5631       C0982   Shreya Mishra          NaN
2772  ORD5681       C0547   Manish Sharma          NaN
2809  ORD2466       C0864    Shreya Verma          NaN
3207  ORD4954       C0227    Aditya Singh          NaN
3318  ORD1592       C0632   Rahul Chauhan          NaN
3770  ORD5885       C0888    Arjun Saxena          NaN
4066  ORD2395       C0270     Pooja Verma          NaN
4157  ORD1815       C1000   Meera Chauhan          NaN
4561  ORD5493       C0710   Varun Chauhan          NaN
4578  ORD3968       C0709     Pooja Patel          NaN
4633  ORD5662       C0097   Manish Tiwari          NaN
4952  ORD4994       C0759     Karan Joshi          NaN
4969  ORD4844       C0375  Simran Agarwal          NaN
4982  ORD2479       C0326    Rahul Mishra          NaN

Checkiing the Valid Payment Modes

In [110]:
df["Payment_Mode"].value_counts()

Payment_Mode
Debit Card     1020
Net Banking    1018
UPI            1009
Credit Card    1003
Cash            950
Name: count, dtype: int64

See the 30 Missing Records

In [111]:
df[df["Payment_Mode"].isnull()][
    ["Order_ID", "Customer_ID", "Customer_Name", "Payment_Mode"]
]

     Order_ID Customer_ID   Customer_Name Payment_Mode
110   ORD4759       C0009     Rohan Yadav          NaN
132   ORD5925       C0349     Rohan Kumar          NaN
232   ORD2630       C0899    Kavita Joshi          NaN
736   ORD3971       C0117     Sneha Singh          NaN
738   ORD1512       C0749     Priya Kumar          NaN
1065  ORD2025       C0140    Arjun Tiwari          NaN
1240  ORD3806       C0479    Anjali Verma          NaN
1406  ORD2505       C0104   Karan Agarwal          NaN
1626  ORD1499       C0619    Aditya Kumar          NaN
1754  ORD3760       C0117     Sneha Singh          NaN
1819  ORD2212       C0142    Priya Tiwari          NaN
1907  ORD2367       C0399     Varun Singh          NaN
2049  ORD5289       C0132     Meera Mehta          NaN
2210  ORD5278       C0516    Meera Tiwari          NaN
2345  ORD3588       C0030   Aditya Saxena          NaN
2556  ORD5682       C0695   Manish Tiwari          NaN
2564  ORD5631       C0982   Shreya Mishra          NaN
2772  ORD5681       C0547   Manish Sharma          NaN
2809  ORD2466       C0864    Shreya Verma          NaN
3207  ORD4954       C0227    Aditya Singh          NaN
3318  ORD1592       C0632   Rahul Chauhan          NaN
3770  ORD5885       C0888    Arjun Saxena          NaN
4066  ORD2395       C0270     Pooja Verma          NaN
4157  ORD1815       C1000   Meera Chauhan          NaN
4561  ORD5493       C0710   Varun Chauhan          NaN
4578  ORD3968       C0709     Pooja Patel          NaN
4633  ORD5662       C0097   Manish Tiwari          NaN
4952  ORD4994       C0759     Karan Joshi          NaN
4969  ORD4844       C0375  Simran Agarwal          NaN
4982  ORD2479       C0326    Rahul Mishra          NaN

Check Whether Customer History Is Consistent

In [112]:
payment_check = df.groupby("Customer_ID")["Payment_Mode"].nunique()

check customers with missing payment modes:

In [113]:
missing_payment_customers = df[
    df["Payment_Mode"].isnull()
]["Customer_ID"].unique()

In [114]:
payment_check.loc[
    payment_check.index.isin(missing_payment_customers)
].value_counts()

Payment_Mode
3    9
4    7
2    6
1    4
5    3
Name: count, dtype: int64

Let's See the Actual Payment History

In [115]:
df[df["Customer_ID"].isin(
    missing_payment_customers
)][
    ["Customer_ID", "Customer_Name", "Payment_Mode"]
].sort_values("Customer_ID")

     Customer_ID  Customer_Name Payment_Mode
7          C0009    Rohan Yadav  Net Banking
1198       C0009    Rohan Yadav  Credit Card
589        C0009    Rahul Singh         Cash
2108       C0009    Rohan Yadav          UPI
2585       C0009    Rohan Yadav  Net Banking
...          ...            ...          ...
466        C1000  Meera Chauhan         Cash
4157       C1000  Meera Chauhan          NaN
2492       C1000  Meera Chauhan  Credit Card
1579       C1000  Meera Chauhan         Cash
2422       C1000  Meera Chauhan  Credit Card

[176 rows x 3 columns]

Create a Payment Missing Flag

In [116]:
df["Payment_Mode_Missing"] = df["Payment_Mode"].isnull()

In [117]:
df["Payment_Mode_Missing"].value_counts()

Payment_Mode_Missing
False    5000
True       30
Name: count, dtype: int64

In [120]:
df.isnull().sum()

Order_ID                 0
Order_Date               0
Customer_ID              0
Customer_Name            0
Product                  0
Category                 0
Quantity                45
Unit_Price               0
Cost_Price               0
Discount                 0
City                     0
State                    0
Region                   0
Salesperson              0
Payment_Mode            30
Quantity_Missing         0
Payment_Mode_Missing     0
dtype: int64

In [121]:
df[df.duplicated(keep=False)]

,Order_ID,Order_Date,Customer_ID,Customer_Name,Product,Category,Quantity,Unit_Price,Cost_Price,Discount,City,State,Region,Salesperson,Payment_Mode,Quantity_Missing,Payment_Mode_Missing
8,ORD1200,2026-08-01,C0080,Rohan Yadav,Office Chair,Furniture,1.0,12000.0,8500,0,Lucknow,Uttar Pradesh,North,Karan,Debit Card,False,False
112,ORD5280,2026-01-14,C0863,Manish Joshi,Notebook,Stationery,7.0,120.0,65,15,Chennai,Tamil Nadu,South,Neha,Cash,False,False
118,ORD1299,2026-08-28,C0616,Rahul Joshi,Printer,Electronics,1.0,16000.0,12500,15,Bengaluru,Karnataka,South,Amit,Credit Card,False,False
213,ORD4777,2026-06-23,C0828,Anjali Verma,Desk,Furniture,2.0,9000.0,6200,5,Bhubaneswar,Odisha,East,Priya,Debit Card,False,False
237,ORD2788,2026-07-05,C0114,Ravi Verma,Desk,Furniture,4.0,9000.0,6200,20,Ahmedabad,Gujarat,West,Amit,Debit Card,False,False
290,ORD2919,2026-02-09,C0545,Pooja Saxena,Pen Set,Stationery,1.0,250.0,140,20,Chennai,Tamil Nadu,South,Karan,Debit Card,False,False
309,ORD5779,2026-02-09,C0653,Aditya Mehta,Smartphone,Electronics,2.0,28000.0,22000,0,Lucknow,Uttar Pradesh,North,Karan,UPI,False,False
311,ORD4741,2026-08-27,C0141,Anjali Mishra,Laptop,Electronics,3.0,55000.0,45000,15,Ahmedabad,Gujarat,West,Ravi,Credit Card,False,False
560,ORD2035,2026-01-06,C0427,Ravi Joshi,Pen Set,Stationery,2.0,250.0,140,10,Lucknow,Uttar Pradesh,North,Neha,Debit Card,False,False
621,ORD4608,2026-05-19,C0344,Rohan Gupta,Headphones,Electronics,3.0,3500.0,2200,10,Bhubaneswar,Odisha,East,Sneha,Credit Card,False,False
635,ORD1354,2026-05-09,C0039,Vikas Kumar,Notebook,Stationery,4.0,120.0,65,15,Hyderabad,Telangana,South,Sneha,Net Banking,False,False
636,ORD1312,2026-04-04,C0780,Sneha Verma,Notebook,Stationery,4.0,120.0,65,0,Kolkata,West Bengal,East,Neha,Debit Card,False,False
661,ORD3903,2026-01-28,C0948,Aditya Mishra,Office Chair,Furniture,1.0,12000.0,8500,15,Kolkata,West Bengal,East,Ravi,Debit Card,False,False
776,ORD3493,2026-03-31,C0762,Sneha Patel,Laptop,Electronics,2.0,16000.0,12500,20,Kolkata,West Bengal,East,Priya,UPI,False,False
796,ORD1299,2026-08-28,C0616,Rahul Joshi,Printer,Electronics,1.0,16000.0,12500,15,Bengaluru,Karnataka,South,Amit,Credit Card,False,False
978,ORD2196,2026-04-24,C0421,Priya Kumar,Laptop,Electronics,1.0,55000.0,45000,10,Kolkata,West Bengal,East,Ravi,UPI,False,False
988,ORD3915,2026-08-02,C0005,Priya Mishra,Notebook,Stationery,4.0,120.0,65,10,Lucknow,Uttar Pradesh,North,Sneha,Credit Card,False,False
1177,ORD5349,2026-07-12,C0734,Meera Verma,Desk,Furniture,3.0,9000.0,6200,15,Bengaluru,Karnataka,South,Sneha,Debit Card,False,False
1199,ORD5349,2026-07-12,C0734,Meera Verma,Desk,Furniture,3.0,9000.0,6200,15,Bengaluru,Karnataka,South,Sneha,Debit Card,False,False
1208,ORD4931,2026-08-08,C0941,Pooja Saxena,Monitor,Electronics,4.0,18000.0,14000,0,Lucknow,Uttar Pradesh,North,Amit,Cash,False,False
1268,ORD1015,2026-04-13,C0932,Varun Agarwal,Pen Set,Stationery,2.0,250.0,140,15,Jaipur,Rajasthan,North,Amit,Credit Card,False,False
1476,ORD1354,2026-05-09,C0039,Vikas Kumar,Notebook,Stationery,4.0,120.0,65,15,Hyderabad,Telangana,South,Sneha,Net Banking,False,False
1481,ORD2919,2026-02-09,C0545,Pooja Saxena,Pen Set,Stationery,1.0,250.0,140,20,Chennai,Tamil Nadu,South,Karan,Debit Card,False,False
1846,ORD3493,2026-03-31,C0762,Sneha Patel,Laptop,Electronics,2.0,16000.0,12500,20,Kolkata,West Bengal,East,Priya,UPI,False,False
1962,ORD4526,2026-01-29,C0963,Simran Mehta,Monitor,Electronics,4.0,18000.0,14000,20,Jaipur,Rajasthan,North,Neha,Net Banking,False,False
2120,ORD2788,2026-07-05,C0114,Ravi Verma,Desk,Furniture,4.0,9000.0,6200,20,Ahmedabad,Gujarat,West,Amit,Debit Card,False,False
2197,ORD5268,2026-01-17,C0639,Rahul Joshi,Pen Set,Stationery,7.0,250.0,140,0,Mumbai,Maharashtra,West,Karan,Net Banking,False,False
2324,ORD3907,2026-07-20,C0394,Shreya Saxena,Laptop,Electronics,7.0,55000.0,45000,15,Bengaluru,Karnataka,South,Priya,Credit Card,False,False
2523,ORD3321,2026-03-24,C0058,Manish Sharma,Keyboard,Electronics,6.0,1800.0,1100,0,Hyderabad,Telangana,South,Neha,UPI,False,False
2531,ORD4530,2026-08-04,C0692,Simran Joshi,Notebook,Stationery,1.0,120.0,65,10,Delhi,Delhi,North,Amit,UPI,False,False
2678,ORD4526,2026-01-29,C0963,Simran Mehta,Monitor,Electronics,4.0,18000.0,14000,20,Jaipur,Rajasthan,North,Neha,Net Banking,False,False
2832,ORD5092,2026-02-05,C0014,Aditya Singh,Pen Set,Stationery,2.0,250.0,140,20,Mumbai,Maharashtra,West,Priya,Net Banking,False,False
2863,ORD3903,2026-01-28,C0948,Aditya Mishra,Office Chair,Furniture,1.0,12000.0,8500,15,Kolkata,West Bengal,East,Ravi,Debit Card,False,False
2888,ORD3579,2026-04-30,C0391,Pooja Saxena,Desk,Furniture,1.0,9000.0,6200,15,Bhubaneswar,Odisha,East,Neha,Net Banking,False,False
2904,ORD4534,2026-06-05,C0142,Priya Tiwari,Pen Set,Stationery,4.0,250.0,140,0,Bengaluru,Karnataka,South,Sneha,Net Banking,False,False
2914,ORD2196,2026-04-24,C0421,Priya Kumar,Laptop,Electronics,1.0,55000.0,45000,10,Kolkata,West Bengal,East,Ravi,UPI,False,False
2932,ORD5779,2026-02-09,C0653,Aditya Mehta,Smartphone,Electronics,2.0,28000.0,22000,0,Lucknow,Uttar Pradesh,North,Karan,UPI,False,False
2942,ORD4931,2026-08-08,C0941,Pooja Saxena,Monitor,Electronics,4.0,18000.0,14000,0,Lucknow,Uttar Pradesh,North,Amit,Cash,False,False
3010,ORD2035,2026-01-06,C0427,Ravi Joshi,Pen Set,Stationery,2.0,250.0,140,10,Lucknow,Uttar Pradesh,North,Neha,Debit Card,False,False
3066,ORD5234,2026-01-01,C0288,Neha Chauhan,Pen Set,Stationery,3.0,250.0,140,20,Chennai,Tamil Nadu,South,Priya,Debit Card,False,False
3102,ORD5234,2026-01-01,C0288,Neha Chauhan,Pen Set,Stationery,3.0,250.0,140,20,Chennai,Tamil Nadu,South,Priya,Debit Card,False,False
3119,ORD3579,2026-04-30,C0391,Pooja Saxena,Desk,Furniture,1.0,9000.0,6200,15,Bhubaneswar,Odisha,East,Neha,Net Banking,False,False
3229,ORD3321,2026-03-24,C0058,Manish Sharma,Keyboard,Electronics,6.0,1800.0,1100,0,Hyderabad,Telangana,South,Neha,UPI,False,False
3231,ORD1312,2026-04-04,C0780,Sneha Verma,Notebook,Stationery,4.0,120.0,65,0,Kolkata,West Bengal,East,Neha,Debit Card,False,False
3349,ORD1200,2026-08-01,C0080,Rohan Yadav,Office Chair,Furniture,1.0,12000.0,8500,0,Lucknow,Uttar Pradesh,North,Karan,Debit Card,False,False
3711,ORD1251,2026-01-26,C0820,Manish Joshi,Pen Set,Stationery,4.0,250.0,140,5,Gorakhpur,Uttar Pradesh,North,Amit,Credit Card,False,False
3820,ORD1015,2026-04-13,C0932,Varun Agarwal,Pen Set,Stationery,2.0,250.0,140,15,Jaipur,Rajasthan,North,Amit,Credit Card,False,False
3877,ORD4777,2026-06-23,C0828,Anjali Verma,Desk,Furniture,2.0,9000.0,6200,5,Bhubaneswar,Odisha,East,Priya,Debit Card,False,False
3881,ORD1130,2026-08-07,C0301,Arjun Yadav,Smartphone,Electronics,7.0,28000.0,22000,0,Bengaluru,Karnataka,South,Amit,UPI,False,False
3934,ORD5092,2026-02-05,C0014,Aditya Singh,Pen Set,Stationery,2.0,250.0,140,20,Mumbai,Maharashtra,West,Priya,Net Banking,False,False
3977,ORD4608,2026-05-19,C0344,Rohan Gupta,Headphones,Electronics,3.0,3500.0,2200,10,Bhubaneswar,Odisha,East,Sneha,Credit Card,False,False
3982,ORD4741,2026-08-27,C0141,Anjali Mishra,Laptop,Electronics,3.0,55000.0,45000,15,Ahmedabad,Gujarat,West,Ravi,Credit Card,False,False
4110,ORD5268,2026-01-17,C0639,Rahul Joshi,Pen Set,Stationery,7.0,250.0,140,0,Mumbai,Maharashtra,West,Karan,Net Banking,False,False
4136,ORD4534,2026-06-05,C0142,Priya Tiwari,Pen Set,Stationery,4.0,250.0,140,0,Bengaluru,Karnataka,South,Sneha,Net Banking,False,False
4150,ORD1251,2026-01-26,C0820,Manish Joshi,Pen Set,Stationery,4.0,250.0,140,5,Gorakhpur,Uttar Pradesh,North,Amit,Credit Card,False,False
4566,ORD3915,2026-08-02,C0005,Priya Mishra,Notebook,Stationery,4.0,120.0,65,10,Lucknow,Uttar Pradesh,North,Sneha,Credit Card,False,False
4734,ORD4530,2026-08-04,C0692,Simran Joshi,Notebook,Stationery,1.0,120.0,65,10,Delhi,Delhi,North,Amit,UPI,False,False
4749,ORD3907,2026-07-20,C0394,Shreya Saxena,Laptop,Electronics,7.0,55000.0,45000,15,Bengaluru,Karnataka,South,Priya,Credit Card,False,False
4772,ORD5280,2026-01-14,C0863,Manish Joshi,Notebook,Stationery,7.0,120.0,65,15,Chennai,Tamil Nadu,South,Neha,Cash,False,False
4824,ORD1130,2026-08-07,C0301,Arjun Yadav,Smartphone,Electronics,7.0,28000.0,22000,0,Bengaluru,Karnataka,South,Amit,UPI,False,False

In [123]:
df[df.duplicated(keep=False)].shape

(60, 17)

Check Duplicate Order IDs

In [124]:
df["Order_ID"].duplicated().sum()

np.int64(30)

In [126]:
df.duplicated().sum()

np.int64(30)

Find Repeated Order IDs

In [127]:
df[df["Order_ID"].duplicated(keep=False)][
    ["Order_ID", "Order_Date", "Customer_ID", "Product", "Quantity"]
]

     Order_ID  Order_Date Customer_ID       Product  Quantity
8     ORD1200  2026-08-01       C0080  Office Chair       1.0
112   ORD5280  2026-01-14       C0863      Notebook       7.0
118   ORD1299  2026-08-28       C0616       Printer       1.0
213   ORD4777  2026-06-23       C0828          Desk       2.0
237   ORD2788  2026-07-05       C0114          Desk       4.0
290   ORD2919  2026-02-09       C0545       Pen Set       1.0
309   ORD5779  2026-02-09       C0653    Smartphone       2.0
311   ORD4741  2026-08-27       C0141        Laptop       3.0
560   ORD2035  2026-01-06       C0427       Pen Set       2.0
621   ORD4608  2026-05-19       C0344    Headphones       3.0
635   ORD1354  2026-05-09       C0039      Notebook       4.0
636   ORD1312  2026-04-04       C0780      Notebook       4.0
661   ORD3903  2026-01-28       C0948  Office Chair       1.0
776   ORD3493  2026-03-31       C0762        Laptop       2.0
796   ORD1299  2026-08-28       C0616       Printer       1.0
978   ORD2196  2026-04-24       C0421        Laptop       1.0
988   ORD3915  2026-08-02       C0005      Notebook       4.0
1177  ORD5349  2026-07-12       C0734          Desk       3.0
1199  ORD5349  2026-07-12       C0734          Desk       3.0
1208  ORD4931  2026-08-08       C0941       Monitor       4.0
1268  ORD1015  2026-04-13       C0932       Pen Set       2.0
1476  ORD1354  2026-05-09       C0039      Notebook       4.0
1481  ORD2919  2026-02-09       C0545       Pen Set       1.0
1846  ORD3493  2026-03-31       C0762        Laptop       2.0
1962  ORD4526  2026-01-29       C0963       Monitor       4.0
2120  ORD2788  2026-07-05       C0114          Desk       4.0
2197  ORD5268  2026-01-17       C0639       Pen Set       7.0
2324  ORD3907  2026-07-20       C0394        Laptop       7.0
2523  ORD3321  2026-03-24       C0058      Keyboard       6.0
2531  ORD4530  2026-08-04       C0692      Notebook       1.0
2678  ORD4526  2026-01-29       C0963       Monitor       4.0
2832  ORD5092  2026-02-05       C0014       Pen Set       2.0
2863  ORD3903  2026-01-28       C0948  Office Chair       1.0
2888  ORD3579  2026-04-30       C0391          Desk       1.0
2904  ORD4534  2026-06-05       C0142       Pen Set       4.0
2914  ORD2196  2026-04-24       C0421        Laptop       1.0
2932  ORD5779  2026-02-09       C0653    Smartphone       2.0
2942  ORD4931  2026-08-08       C0941       Monitor       4.0
3010  ORD2035  2026-01-06       C0427       Pen Set       2.0
3066  ORD5234  2026-01-01       C0288       Pen Set       3.0
3102  ORD5234  2026-01-01       C0288       Pen Set       3.0
3119  ORD3579  2026-04-30       C0391          Desk       1.0
3229  ORD3321  2026-03-24       C0058      Keyboard       6.0
3231  ORD1312  2026-04-04       C0780      Notebook       4.0
3349  ORD1200  2026-08-01       C0080  Office Chair       1.0
3711  ORD1251  2026-01-26       C0820       Pen Set       4.0
3820  ORD1015  2026-04-13       C0932       Pen Set       2.0
3877  ORD4777  2026-06-23       C0828          Desk       2.0
3881  ORD1130  2026-08-07       C0301    Smartphone       7.0
3934  ORD5092  2026-02-05       C0014       Pen Set       2.0
3977  ORD4608  2026-05-19       C0344    Headphones       3.0
3982  ORD4741  2026-08-27       C0141        Laptop       3.0
4110  ORD5268  2026-01-17       C0639       Pen Set       7.0
4136  ORD4534  2026-06-05       C0142       Pen Set       4.0
4150  ORD1251  2026-01-26       C0820       Pen Set       4.0
4566  ORD3915  2026-08-02       C0005      Notebook       4.0
4734  ORD4530  2026-08-04       C0692      Notebook       1.0
4749  ORD3907  2026-07-20       C0394        Laptop       7.0
4772  ORD5280  2026-01-14       C0863      Notebook       7.0
4824  ORD1130  2026-08-07       C0301    Smartphone       7.0

Check Duplicate Count Again

In [128]:
print("Exact duplicates:", df.duplicated().sum())
print("Duplicate Order IDs:", df["Order_ID"].duplicated().sum())

Exact duplicates: 30
Duplicate Order IDs: 30

If They Are Exact Duplicates

In [129]:
original_rows = len(df)

In [130]:
df = df.drop_duplicates()

In [131]:
print("Before:", original_rows)
print("After:", len(df))

Before: 5030
After: 5000

Verify Dataset Size

In [132]:
df.shape

(5000, 17)

In [133]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Product',
       'Category', 'Quantity', 'Unit_Price', 'Cost_Price', 'Discount', 'City',
       'State', 'Region', 'Salesperson', 'Payment_Mode', 'Quantity_Missing',
       'Payment_Mode_Missing'],
      dtype='str')

Investigate Order_Date

In [134]:
df["Order_Date"].head(20)

0     2026-03-04
1     2026-03-01
2     2026-06-24
3     2026-08-02
4     2026-02-06
5     2026-03-10
6     2026-02-27
7     2026-01-06
8     2026-08-01
9     2026-06-25
10    2026-12-04
11    2026-08-15
12    2026-05-26
13    2026-05-21
14    2026-05-21
15    2026-04-14
16    2026-04-21
17    2026-05-09
18    2026-06-18
19    2026-05-07
Name: Order_Date, dtype: str

In [135]:
df["Order_Date"].unique()[:20]

<StringArray>
['2026-03-04', '2026-03-01', '2026-06-24', '2026-08-02', '2026-02-06',
 '2026-03-10', '2026-02-27', '2026-01-06', '2026-08-01', '2026-06-25',
 '2026-12-04', '2026-08-15', '2026-05-26', '2026-05-21', '2026-04-14',
 '2026-04-21', '2026-05-09', '2026-06-18', '2026-05-07', '2026-03-22']
Length: 20, dtype: str

Count Different Date Formats

In [136]:
df["Order_Date"].astype(str).str.len().value_counts()

Order_Date
10    5000
Name: count, dtype: int64

In [137]:
df["Order_Date"].astype(str).str.contains("/").sum()

np.int64(0)

In [138]:
df["Order_Date"].astype(str).str.contains("-").sum()

np.int64(5000)

Look at Only Non-Standard Dates

YYYY-MM-DD

In [143]:
df[
    ~df["Order_Date"].str.match(r"^\d{4}-\d{2}-\d{2}$", na=False)
]["Order_Date"].head(20)

Series([], Name: Order_Date, dtype: str)

Count the Non-Standard Dates

In [144]:
df[
    ~df["Order_Date"].str.match(r"^\d{4}-\d{2}-\d{2}$", na=False)
].shape[0]

0

Check Whether There Are Impossible Dates

In [145]:
test_dates = pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)

In [146]:
test_dates.isnull().sum()

np.int64(0)

Check the Date Range

In [157]:
print("Minimum date:", test_dates.min())
print("Maximum date:", test_dates.max())

Minimum date: 2026-01-01 00:00:00
Maximum date: 2026-12-06 00:00:00

In [158]:
df["Order_Date"].isnull().sum()

np.int64(0)

Convert the Column

we've confirmed the formats are valid, we can convert the actual column.

In [150]:
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce",
    format="mixed"
)

Validate the Conversion

In [151]:
df["Order_Date"].dtype

dtype('<M8[us]')

In [152]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Product,Category,Quantity,Unit_Price,Cost_Price,Discount,City,State,Region,Salesperson,Payment_Mode,Quantity_Missing,Payment_Mode_Missing
0,ORD3526,2026-03-04,C0223,Sneha Mishra,Office Chair,Furniture,2.0,12000.0,8500,10,Gorakhpur,Uttar Pradesh,North,Sneha,UPI,False,False
1,ORD3923,2026-03-01,C0212,Karan Agarwal,Notebook,Stationery,1.0,120.0,65,10,Delhi,Delhi,North,Priya,Debit Card,False,False
2,ORD1890,2026-06-24,C0015,Rahul Yadav,Smartphone,Electronics,1.0,28000.0,22000,0,Delhi,Delhi,North,Neha,UPI,False,False
3,ORD1658,2026-08-02,C0467,Kavita Singh,Notebook,Stationery,5.0,120.0,65,10,Kolkata,West Bengal,East,Neha,Net Banking,False,False
4,ORD5317,2026-02-06,C0979,Ravi Sharma,Office Chair,Furniture,4.0,12000.0,8500,20,Jaipur,Rajasthan,north,Karan,Net Banking,False,False

Remove Currency Formatting

In [159]:
df["Unit_Price"] = df["Unit_Price"].astype(str).str.replace("₹", "", regex=False)

In [160]:
df["Unit_Price"] = df["Unit_Price"].str.replace(",", "", regex=False)

Convert to Numeric

In [161]:
df["Unit_Price"] = pd.to_numeric(
    df["Unit_Price"],
    errors="coerce"
)

In [162]:
df["Unit_Price"].dtype

dtype('float64')

Validate Unit Price

In [163]:
print("Missing prices:", df["Unit_Price"].isnull().sum())
print("Minimum price:", df["Unit_Price"].min())
print("Maximum price:", df["Unit_Price"].max())

Missing prices: 0
Minimum price: 120.0
Maximum price: 55000.0

Investigate Quantity

In [164]:
df["Quantity"].value_counts().sort_index()

Quantity
-3.0       11
 1.0      701
 2.0      665
 3.0      713
 4.0      732
 5.0      707
 6.0      712
 7.0      706
 999.0      8
Name: count, dtype: int64

In [165]:
df["Quantity"].describe()

count    4955.000000
mean        5.611705
std        40.002672
min        -3.000000
25%         2.000000
50%         4.000000
75%         6.000000
max       999.000000
Name: Quantity, dtype: float64

Find Negative Quantities

In [166]:
df[df["Quantity"] < 0][
    ["Order_ID", "Product", "Quantity"]
]

     Order_ID       Product  Quantity
644   ORD5622      Keyboard      -3.0
1104  ORD1844  Office Chair      -3.0
1184  ORD2967        Laptop      -3.0
1460  ORD5123      Keyboard      -3.0
1792  ORD2217          Desk      -3.0
1856  ORD5086  Office Chair      -3.0
1967  ORD1555    Smartphone      -3.0
2399  ORD1998        Laptop      -3.0
3573  ORD1038       Pen Set      -3.0
3879  ORD2846       Printer      -3.0
4430  ORD5519        Laptop      -3.0

Find the 999 Values

In [167]:
df[df["Quantity"] == 999][
    ["Order_ID", "Product", "Quantity"]
]

     Order_ID     Product  Quantity
1446  ORD3265      Laptop     999.0
1805  ORD2872        Desk     999.0
2259  ORD4859    Notebook     999.0
2778  ORD2767  Smartphone     999.0
3063  ORD4429     Printer     999.0
3321  ORD3937    Notebook     999.0
3351  ORD3549     Pen Set     999.0
4445  ORD2839        Desk     999.0

Check Valid Quantity Range

In [168]:
df["Quantity"].value_counts().sort_index().head(20)

Quantity
-3.0       11
 1.0      701
 2.0      665
 3.0      713
 4.0      732
 5.0      707
 6.0      712
 7.0      706
 999.0      8
Name: count, dtype: int64

In [169]:
df["Quantity"].value_counts().sort_index().tail(20)

Quantity
-3.0       11
 1.0      701
 2.0      665
 3.0      713
 4.0      732
 5.0      707
 6.0      712
 7.0      706
 999.0      8
Name: count, dtype: int64

Handle Negative Quantity

In [170]:
df["Invalid_Quantity"] = df["Quantity"] < 0

In [171]:
df["Invalid_Quantity"].value_counts()

Invalid_Quantity
False    4989
True       11
Name: count, dtype: int64

Investigate Discount

In [172]:
df["Discount"].describe()

count    5000.000000
mean       10.129000
std         9.025223
min         0.000000
25%         5.000000
50%        10.000000
75%        15.000000
max       150.000000
Name: Discount, dtype: float64

In [173]:
df[df["Discount"] > 100][
    ["Order_ID", "Product", "Discount"]
]

     Order_ID     Product  Discount
840   ORD1046  Smartphone       150
941   ORD3389    Keyboard       150
1024  ORD5241    Notebook       150
2864  ORD4627        Desk       150
3339  ORD5957     Monitor       150
3886  ORD5040  Headphones       150
4062  ORD3550     Pen Set       150
4859  ORD2708     Monitor       150

Flag Invalid Discounts

In [174]:
df["Invalid_Discount"] = (
    (df["Discount"] < 0) |
    (df["Discount"] > 100)
)

In [175]:
df["Invalid_Discount"].value_counts()

Invalid_Discount
False    4992
True        8
Name: count, dtype: int64

Check Prices for Negative Values

In [176]:
df[df["Unit_Price"] < 0][
    ["Order_ID", "Product", "Unit_Price"]
]

Empty DataFrame
Columns: [Order_ID, Product, Unit_Price]
Index: []

In [177]:
df[df["Cost_Price"] < 0][
    ["Order_ID", "Product", "Cost_Price"]
]

Empty DataFrame
Columns: [Order_ID, Product, Cost_Price]
Index: []

Quantity: Separate the Problems

Flag Negative Quantities

In [178]:
df["Invalid_Quantity"] = df["Quantity"] < 0

In [179]:
df["Invalid_Quantity"].value_counts()

Invalid_Quantity
False    4989
True       11
Name: count, dtype: int64

Flag Invalid Discounts

In [180]:
df["Invalid_Discount"] = (
    (df["Discount"] < 0) |
    (df["Discount"] > 100)
)

In [181]:
df["Invalid_Discount"].value_counts()

Invalid_Discount
False    4992
True        8
Name: count, dtype: int64

In [182]:
df[df["Invalid_Discount"]][
    ["Order_ID", "Product", "Discount"]
]

     Order_ID     Product  Discount
840   ORD1046  Smartphone       150
941   ORD3389    Keyboard       150
1024  ORD5241    Notebook       150
2864  ORD4627        Desk       150
3339  ORD5957     Monitor       150
3886  ORD5040  Headphones       150
4062  ORD3550     Pen Set       150
4859  ORD2708     Monitor       150

Check Price Validity

In [183]:
df[df["Unit_Price"] <= 0][
    ["Order_ID", "Product", "Unit_Price"]
]

Empty DataFrame
Columns: [Order_ID, Product, Unit_Price]
Index: []

In [184]:
df[df["Cost_Price"] <= 0][
    ["Order_ID", "Product", "Cost_Price"]
]

Empty DataFrame
Columns: [Order_ID, Product, Cost_Price]
Index: []

In [185]:
df["Quantity"].dtype

dtype('float64')

In [186]:
df["Quantity"].describe()

count    4955.000000
mean        5.611705
std        40.002672
min        -3.000000
25%         2.000000
50%         4.000000
75%         6.000000
max       999.000000
Name: Quantity, dtype: float64

In [187]:
Q1 = df["Quantity"].quantile(0.25)
Q3 = df["Quantity"].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 2.0
Q3: 6.0
IQR: 4.0

In [188]:
upper_limit = Q3 + 1.5 * IQR

print("Upper limit:", upper_limit)

Upper limit: 12.0

Identify Quantity Outliers

In [191]:
outliers = df[df["Quantity"] > upper_limit]

outliers[["Order_ID", "Product", "Quantity"]]

     Order_ID     Product  Quantity
1446  ORD3265      Laptop     999.0
1805  ORD2872        Desk     999.0
2259  ORD4859    Notebook     999.0
2778  ORD2767  Smartphone     999.0
3063  ORD4429     Printer     999.0
3321  ORD3937    Notebook     999.0
3351  ORD3549     Pen Set     999.0
4445  ORD2839        Desk     999.0

Make an Outlier Flag

In [192]:
df["Quantity_Outlier"] = df["Quantity"] > upper_limit

In [193]:
df["Quantity_Outlier"].value_counts()

Quantity_Outlier
False    4992
True        8
Name: count, dtype: int64

999 → invalid/outlier → treat as missing

In [194]:
df.loc[df["Quantity_Outlier"], "Quantity"] = np.nan

Handle Negative Quantities

In [196]:
df.loc[df["Invalid_Quantity"], "Quantity"] = np.nan

In [197]:
df["Quantity"].isnull().sum()

np.int64(64)

Clean Invalid Discounts

In [198]:
df.loc[df["Invalid_Discount"], "Discount"] = np.nan

In [199]:
df["Discount"].isnull().sum()

np.int64(8)

Validate the Numerical Values

In [200]:
print("Negative quantities:",
      (df["Quantity"] < 0).sum())

print("Quantities above upper limit:",
      (df["Quantity"] > upper_limit).sum())

print("Invalid discounts:",
      ((df["Discount"] < 0) | (df["Discount"] > 100)).sum())

Negative quantities: 0
Quantities above upper limit: 0
Invalid discounts: 0

Payment_Mode

In [201]:
df["Payment_Mode_Missing"] = df["Payment_Mode"].isnull()

In [202]:
df["Payment_Mode_Missing"].value_counts()

Payment_Mode_Missing
False    4970
True       30
Name: count, dtype: int64

Check Customer Names

In [203]:
df["Customer_Name"].value_counts().head(20)

Customer_Name
Sneha Patel       44
Anjali Verma      44
Amit Yadav        42
Meera Verma       41
Vikas Mishra      41
Nisha Chauhan     40
Pooja Singh       39
Rohan Saxena      38
Rahul Joshi       38
Manish Yadav      38
Meera Tiwari      37
Manish Joshi      37
Karan Sharma      37
Kavita Agarwal    36
Rahul Yadav       35
Anjali Mishra     34
Shreya Agarwal    34
Kavita Tiwari     34
Rohan Kumar       34
Sneha Sharma      34
Name: count, dtype: int64

check names with leading/trailing spaces:

In [204]:
df[df["Customer_Name"].astype(str) != df["Customer_Name"].astype(str).str.strip()][
    ["Customer_ID", "Customer_Name"]
].head(20)

Empty DataFrame
Columns: [Customer_ID, Customer_Name]
Index: []

Check City

In [205]:
df["City"].value_counts()

City
Bengaluru      459
Bhubaneswar    440
Pune           431
Hyderabad      426
Chennai        424
Kolkata        422
Lucknow        419
Mumbai         418
Jaipur         410
Gorakhpur      399
Delhi          382
Ahmedabad      370
Name: count, dtype: int64

In [206]:
df[df["City"].astype(str) != df["City"].astype(str).str.strip()][
    ["City"]
].head(20)

Empty DataFrame
Columns: [City]
Index: []

Check State

In [207]:
df["State"].value_counts()

State
Maharashtra      848
Uttar Pradesh    822
Karnataka        455
Odisha           439
Telangana        430
Tamil Nadu       425
West Bengal      424
Rajasthan        404
Delhi            382
Gujarat          371
Name: count, dtype: int64

In [208]:
df[df["State"].astype(str) != df["State"].astype(str).str.strip()][
    ["State"]
].head(20)

Empty DataFrame
Columns: [State]
Index: []

Check Region

In [209]:
df["Region"].value_counts()

Region
North      1578
South      1288
West       1204
East        850
 North       33
north        28
NORTH        19
Name: count, dtype: int64

In [210]:
df[df["Region"].astype(str) != df["Region"].astype(str).str.strip()][
    ["Region"]
].head(20)

       Region
29     North
372    North
553    North
632    North
761    North
1218   North
1734   North
2068   North
2320   North
2391   North
2395   North
2480   North
2578   North
2583   North
2631   North
2635   North
2691   North
3443   North
3492   North
3505   North

Check Payment Mode

In [211]:
df["Payment_Mode"].value_counts()

Payment_Mode
Net Banking    1012
Debit Card     1011
UPI            1003
Credit Card     996
Cash            948
Name: count, dtype: int64

Check Salesperson

In [212]:
df["Salesperson"].value_counts().head(20)

Salesperson
Ravi     867
Sneha    865
Priya    865
Amit     822
Karan    794
Neha     787
Name: count, dtype: int64

Standardize City

In [213]:
df["City"] = df["City"].str.strip().str.title()

Standardize State

In [214]:
df["State"] = df["State"].str.strip().str.title()

Standardize Region

In [215]:
df["Region"] = df["Region"].str.strip().str.title()

In [216]:
df["City"].value_counts()

City
Bengaluru      459
Bhubaneswar    440
Pune           431
Hyderabad      426
Chennai        424
Kolkata        422
Lucknow        419
Mumbai         418
Jaipur         410
Gorakhpur      399
Delhi          382
Ahmedabad      370
Name: count, dtype: int64

In [217]:
df["State"].value_counts()

State
Maharashtra      848
Uttar Pradesh    822
Karnataka        455
Odisha           439
Telangana        430
Tamil Nadu       425
West Bengal      424
Rajasthan        404
Delhi            382
Gujarat          371
Name: count, dtype: int64

In [218]:
df["Region"].value_counts()

Region
North    1658
South    1288
West     1204
East      850
Name: count, dtype: int64

Standardize Customer Name

In [219]:
df["Customer_Name"] = df["Customer_Name"].str.strip().str.title()

Standardize Salesperson

In [220]:
df["Salesperson"] = df["Salesperson"].str.strip().str.title()

Payment Mode

In [221]:
payment_map = {
    "upi": "UPI",
    "cash": "Cash",
    "credit card": "Credit Card",
    "debit card": "Debit Card",
    "net banking": "Net Banking"
}

In [222]:
df["Payment_Mode"] = (
    df["Payment_Mode"]
    .str.strip()
    .str.lower()
    .map(payment_map)
)

Standardize Product and Category

In [226]:
df["Product"].value_counts()

Product
Laptop          584
Office Chair    517
Headphones      517
Notebook        509
Keyboard        500
Monitor         493
Pen Set         480
Smartphone      476
Desk            463
Printer         461
Name: count, dtype: int64

In [225]:
df["Product"] = df["Product"].str.strip().str.title()

In [228]:
df["Category"].value_counts()

Category
Electronics    3041
Stationery      983
Furniture       976
Name: count, dtype: int64

In [227]:
df["Category"] = df["Category"].str.strip().str.title()

In [229]:
print(df["City"].nunique())
print(df["State"].nunique())
print(df["Region"].nunique())
print(df["Payment_Mode"].nunique())
print(df["Category"].nunique())

12
10
4
5
3

Check Payment Mode

In [230]:
df["Payment_Mode"].value_counts(dropna=False)

Payment_Mode
Net Banking    1012
Debit Card     1011
UPI            1003
Credit Card     996
Cash            948
NaN              30
Name: count, dtype: int64

In [231]:
print(df["Customer_Name"].nunique())
print(df["Product"].nunique())
print(df["Category"].nunique())
print(df["City"].nunique())
print(df["State"].nunique())
print(df["Region"].nunique())
print(df["Salesperson"].nunique())
print(df["Payment_Mode"].nunique())

274
10
3
12
10
4
6
5

In [232]:
df["Unit_Price"].describe()

count     5000.000000
mean     14579.778000
std      16384.520684
min        120.000000
25%       1800.000000
50%      12000.000000
75%      18000.000000
max      55000.000000
Name: Unit_Price, dtype: float64

In [233]:
df["Cost_Price"].describe()

count     5000.000000
mean     11280.614000
std      13394.026033
min         65.000000
25%       1100.000000
50%       8500.000000
75%      14000.000000
max      45000.000000
Name: Cost_Price, dtype: float64

In [234]:
df.groupby("Product")["Unit_Price"].agg(
    ["min", "max", "mean"]
)

                  min      max          mean
Product
Desk           9000.0   9000.0   9000.000000
Headphones     3500.0   3500.0   3500.000000
Keyboard       1800.0  55000.0   2012.800000
Laptop          120.0  55000.0  50754.109589
Monitor       18000.0  18000.0  18000.000000
Notebook        120.0  55000.0    335.638507
Office Chair  12000.0  55000.0  12083.172147
Pen Set         250.0  55000.0    364.062500
Printer       16000.0  55000.0  16169.197397
Smartphone    28000.0  55000.0  28056.722689

In [235]:
df.groupby("Product")["Cost_Price"].agg(
    ["min", "max", "mean"]
)

                min    max          mean
Product
Desk           6200   6200   6200.000000
Headphones     2200   2200   2200.000000
Keyboard       1100   1100   1100.000000
Laptop           65  45000  41461.960616
Monitor       14000  14000  14000.000000
Notebook         65     65     65.000000
Office Chair   8500   8500   8500.000000
Pen Set         140    140    140.000000
Printer       12500  12500  12500.000000
Smartphone    22000  22000  22000.000000

In [236]:
df[df["Unit_Price"] < df["Cost_Price"]][
    ["Order_ID", "Product", "Unit_Price", "Cost_Price"]
]

Empty DataFrame
Columns: [Order_ID, Product, Unit_Price, Cost_Price]
Index: []

In [240]:
df.isnull().sum()

Order_ID                 0
Order_Date               0
Customer_ID              0
Customer_Name            0
Product                  0
Category                 0
Quantity                64
Unit_Price               0
Cost_Price               0
Discount                 8
City                     0
State                    0
Region                   0
Salesperson              0
Payment_Mode            30
Quantity_Missing         0
Payment_Mode_Missing     0
Invalid_Quantity         0
Invalid_Discount         0
Quantity_Outlier         0
dtype: int64

Quantity: Investigate the 64 Missing Valu

In [241]:
df[df["Quantity"].isnull()][
    ["Order_ID", "Customer_ID", "Customer_Name",
     "Product", "Category", "Unit_Price", "Cost_Price"]
].head(20)

,Order_ID,Customer_ID,Customer_Name,Product,Category,Unit_Price,Cost_Price
100,ORD1298,C0385,Meera Joshi,Desk,Furniture,9000.0,6200
163,ORD4500,C0483,Nisha Patel,Desk,Furniture,9000.0,6200
391,ORD5710,C0360,Shreya Gupta,Monitor,Electronics,18000.0,14000
456,ORD1388,C0661,Nisha Gupta,Monitor,Electronics,18000.0,14000
461,ORD5465,C0595,Amit Mishra,Desk,Furniture,9000.0,6200
469,ORD4025,C0477,Amit Chauhan,Printer,Electronics,16000.0,12500
489,ORD3933,C0239,Neha Agarwal,Printer,Electronics,16000.0,12500
552,ORD4154,C0482,Manish Chauhan,Pen Set,Stationery,250.0,140
644,ORD5622,C0266,Sneha Tiwari,Keyboard,Electronics,1800.0,1100
714,ORD4047,C0743,Anjali Tiwari,Headphones,Electronics,3500.0,2200
725,ORD1121,C0073,Karan Gupta,Desk,Furniture,9000.0,6200
819,ORD1379,C0219,Karan Verma,Notebook,Stationery,120.0,65
884,ORD3742,C0002,Amit Saxena,Headphones,Electronics,3500.0,2200
942,ORD3154,C0643,Rahul Gupta,Printer,Electronics,16000.0,12500
949,ORD5295,C0781,Sneha Kumar,Office Chair,Furniture,12000.0,8500
1104,ORD1844,C0611,Neha Verma,Office Chair,Furniture,12000.0,8500
1182,ORD5555,C0321,Manish Tiwari,Laptop,Electronics,55000.0,45000
1184,ORD2967,C0761,Sneha Verma,Laptop,Electronics,55000.0,45000
1354,ORD4076,C0233,Amit Sharma,Smartphone,Electronics,28000.0,22000
1376,ORD1565,C0261,Nisha Yadav,Desk,Furniture,9000.0,6200

Check Quantity by Product

In [242]:
df.groupby("Product")["Quantity"].agg(
    ["count", "mean", "median", "min", "max"]
)

              count      mean  median  min  max
Product
Desk            452  3.922566     4.0  1.0  7.0
Headphones      513  3.937622     4.0  1.0  7.0
Keyboard        495  3.959596     4.0  1.0  7.0
Laptop          577  4.159445     4.0  1.0  7.0
Monitor         488  3.995902     4.0  1.0  7.0
Notebook        504  4.049603     4.0  1.0  7.0
Office Chair    507  3.923077     4.0  1.0  7.0
Pen Set         476  4.130252     4.0  1.0  7.0
Printer         454  4.092511     4.0  1.0  7.0
Smartphone      470  4.021277     4.0  1.0  7.0

Check the Missing Quantity Distribution

In [243]:
df[df["Quantity"].isnull()]["Product"].value_counts()

Product
Desk            11
Office Chair    10
Printer          7
Laptop           7
Smartphone       6
Monitor          5
Keyboard         5
Notebook         5
Pen Set          4
Headphones       4
Name: count, dtype: int64

Payment Mode: Investigate the 30 Missing Values

In [244]:
payment_history = df.groupby(
    "Customer_ID"
)["Payment_Mode"].value_counts()
payment_history.head(20)

Customer_ID  Payment_Mode
C0001        Cash            3
             UPI             2
             Debit Card      1
C0002        UPI             2
             Cash            2
             Debit Card      1
             Credit Card     1
C0003        UPI             2
             Net Banking     1
             Credit Card     1
C0004        Net Banking     2
             UPI             2
             Cash            1
             Debit Card      1
C0005        Credit Card     3
             UPI             3
             Cash            1
C0006        Net Banking     5
             Debit Card      2
             Cash            1
Name: count, dtype: int64

Find the Most Common Payment Mode

In [245]:
customer_payment = df.groupby(
    "Customer_ID"
)["Payment_Mode"].agg(
    lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan
)

In [246]:
missing_payment = df[df["Payment_Mode"].isnull()].copy()

missing_payment["Usual_Payment_Mode"] = (
    missing_payment["Customer_ID"].map(customer_payment)
)

missing_payment[
    ["Order_ID", "Customer_ID", "Customer_Name",
     "Payment_Mode", "Usual_Payment_Mode"]
]

     Order_ID Customer_ID   Customer_Name Payment_Mode Usual_Payment_Mode
110   ORD4759       C0009     Rohan Yadav          NaN        Net Banking
132   ORD5925       C0349     Rohan Kumar          NaN               Cash
232   ORD2630       C0899    Kavita Joshi          NaN        Credit Card
736   ORD3971       C0117     Sneha Singh          NaN                UPI
738   ORD1512       C0749     Priya Kumar          NaN        Credit Card
1065  ORD2025       C0140    Arjun Tiwari          NaN         Debit Card
1240  ORD3806       C0479    Anjali Verma          NaN         Debit Card
1406  ORD2505       C0104   Karan Agarwal          NaN        Net Banking
1626  ORD1499       C0619    Aditya Kumar          NaN         Debit Card
1754  ORD3760       C0117     Sneha Singh          NaN                UPI
1819  ORD2212       C0142    Priya Tiwari          NaN               Cash
1907  ORD2367       C0399     Varun Singh          NaN        Net Banking
2049  ORD5289       C0132     Meera Mehta          NaN                UPI
2210  ORD5278       C0516    Meera Tiwari          NaN        Net Banking
2345  ORD3588       C0030   Aditya Saxena          NaN               Cash
2556  ORD5682       C0695   Manish Tiwari          NaN               Cash
2564  ORD5631       C0982   Shreya Mishra          NaN               Cash
2772  ORD5681       C0547   Manish Sharma          NaN         Debit Card
2809  ORD2466       C0864    Shreya Verma          NaN               Cash
3207  ORD4954       C0227    Aditya Singh          NaN        Net Banking
3318  ORD1592       C0632   Rahul Chauhan          NaN        Net Banking
3770  ORD5885       C0888    Arjun Saxena          NaN                UPI
4066  ORD2395       C0270     Pooja Verma          NaN               Cash
4157  ORD1815       C1000   Meera Chauhan          NaN               Cash
4561  ORD5493       C0710   Varun Chauhan          NaN                UPI
4578  ORD3968       C0709     Pooja Patel          NaN               Cash
4633  ORD5662       C0097   Manish Tiwari          NaN        Net Banking
4952  ORD4994       C0759     Karan Joshi          NaN               Cash
4969  ORD4844       C0375  Simran Agarwal          NaN               Cash
4982  ORD2479       C0326    Rahul Mishra          NaN        Credit Card

Find the Typical Quantity for Each Product

In [247]:
df.groupby("Product")["Quantity"].median()

Product
Desk            4.0
Headphones      4.0
Keyboard        4.0
Laptop          4.0
Monitor         4.0
Notebook        4.0
Office Chair    4.0
Pen Set         4.0
Printer         4.0
Smartphone      4.0
Name: Quantity, dtype: float64

See Which Products Have Missing Quantity

In [248]:
df[df["Quantity"].isnull()]["Product"].value_counts()

Product
Desk            11
Office Chair    10
Printer          7
Laptop           7
Smartphone       6
Monitor          5
Keyboard         5
Notebook         5
Pen Set          4
Headphones       4
Name: count, dtype: int64

Create Product Median

In [249]:
product_median = df.groupby("Product")["Quantity"].median()

Fill Missing Quantity

In [250]:
df["Quantity"] = df["Quantity"].fillna(
    df["Product"].map(product_median)
)

In [251]:
df["Quantity"].isnull().sum()

np.int64(0)

Find Each Customer's Most Common Payment Mode

In [252]:
customer_payment = df.groupby(
    "Customer_ID"
)["Payment_Mode"].agg(
    lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan
)
customer_payment.head(10)

Customer_ID
C0001           Cash
C0002           Cash
C0003            UPI
C0004    Net Banking
C0005    Credit Card
C0006    Net Banking
C0007           Cash
C0008    Net Banking
C0009    Net Banking
C0010    Credit Card
Name: Payment_Mode, dtype: str

Fill Missing Payment Modes

In [253]:
df["Payment_Mode"] = df["Payment_Mode"].fillna(
    df["Customer_ID"].map(customer_payment)
)

In [254]:
df["Payment_Mode"].isnull().sum()

np.int64(0)

In [255]:
df["Payment_Mode"].value_counts()

Payment_Mode
Net Banking    1019
Debit Card     1015
UPI            1008
Credit Card     999
Cash            959
Name: count, dtype: int64

In [256]:
df.isnull().sum()

Order_ID                0
Order_Date              0
Customer_ID             0
Customer_Name           0
Product                 0
Category                0
Quantity                0
Unit_Price              0
Cost_Price              0
Discount                8
City                    0
State                   0
Region                  0
Salesperson             0
Payment_Mode            0
Quantity_Missing        0
Payment_Mode_Missing    0
Invalid_Quantity        0
Invalid_Discount        0
Quantity_Outlier        0
dtype: int64

In [257]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 5000
Columns: 20

Investigate Missing Discount

In [258]:
df[df["Discount"].isnull()][
    ["Order_ID", "Product", "Category", "Quantity",
     "Unit_Price", "Cost_Price", "Discount"]
]

,Order_ID,Product,Category,Quantity,Unit_Price,Cost_Price,Discount
840,ORD1046,Smartphone,Electronics,5.0,28000.0,22000,NaN
941,ORD3389,Keyboard,Electronics,7.0,1800.0,1100,NaN
1024,ORD5241,Notebook,Stationery,4.0,120.0,65,NaN
2864,ORD4627,Desk,Furniture,6.0,9000.0,6200,NaN
3339,ORD5957,Monitor,Electronics,1.0,18000.0,14000,NaN
3886,ORD5040,Headphones,Electronics,3.0,3500.0,2200,NaN
4062,ORD3550,Pen Set,Stationery,4.0,250.0,140,NaN
4859,ORD2708,Monitor,Electronics,7.0,18000.0,14000,NaN

Look at Normal Discount Patterns

In [259]:
df.groupby("Product")["Discount"].agg(
    ["count", "mean", "median", "min", "max"]
)

              count       mean  median  min   max
Product
Desk            462   9.632035    10.0  0.0  20.0
Headphones      516  10.106589    10.0  0.0  20.0
Keyboard        499   9.819639    10.0  0.0  20.0
Laptop          584   9.503425    10.0  0.0  20.0
Monitor         491  10.081466    10.0  0.0  20.0
Notebook        508   9.901575    10.0  0.0  20.0
Office Chair    517   9.951644    10.0  0.0  20.0
Pen Set         479  10.323591    10.0  0.0  20.0
Printer         461   9.967462    10.0  0.0  20.0
Smartphone      475   9.821053    10.0  0.0  20.0

In [260]:
df[df["Discount"].isnull()]["Product"].value_counts()

Product
Monitor       2
Smartphone    1
Keyboard      1
Notebook      1
Desk          1
Headphones    1
Pen Set       1
Name: count, dtype: int64

Fill Missing Discount

In [261]:
product_discount = df.groupby("Product")["Discount"].median()

In [262]:
df["Discount"] = df["Discount"].fillna(
    df["Product"].map(product_discount)
)

In [263]:
df["Discount"].isnull().sum()

np.int64(0)

In [264]:
df["Discount"].value_counts().sort_index()

Discount
0.0     1019
5.0     1012
10.0    1002
15.0     979
20.0     988
Name: count, dtype: int64

Validate Discount Rules

In [266]:
print("Discount < 0:  ",
      (df["Discount"] < 0).sum())

print("Discount > 100:  ",
      (df["Discount"] > 100).sum())

Discount < 0:   0
Discount > 100:   0

Main Dataset Missing Values , Duplicate Rows

In [267]:
df.isnull().sum()

Order_ID                0
Order_Date              0
Customer_ID             0
Customer_Name           0
Product                 0
Category                0
Quantity                0
Unit_Price              0
Cost_Price              0
Discount                0
City                    0
State                   0
Region                  0
Salesperson             0
Payment_Mode            0
Quantity_Missing        0
Payment_Mode_Missing    0
Invalid_Quantity        0
Invalid_Discount        0
Quantity_Outlier        0
dtype: int64

In [268]:
df.duplicated().sum()

np.int64(0)

In [269]:
df["Order_ID"].duplicated().sum()

np.int64(0)

Validate Quantity

In [270]:
print("Missing:", df["Quantity"].isnull().sum())
print("Negative:", (df["Quantity"] < 0).sum())
print("999 values:", (df["Quantity"] == 999).sum())

Missing: 0
Negative: 0
999 values: 0

Validate Prices

In [271]:
print("Missing Unit Price:",
      df["Unit_Price"].isnull().sum())

print("Missing Cost Price:",
      df["Cost_Price"].isnull().sum())

print("Unit Price <= 0:",
      (df["Unit_Price"] <= 0).sum())

print("Cost Price <= 0:",
      (df["Cost_Price"] <= 0).sum())

Missing Unit Price: 0
Missing Cost Price: 0
Unit Price <= 0: 0
Cost Price <= 0: 0

Validate Dates

In [272]:
print("Missing dates:",
      df["Order_Date"].isnull().sum())

print("Date type:",
      df["Order_Date"].dtype)

print("Minimum date:",
      df["Order_Date"].min())

print("Maximum date:",
      df["Order_Date"].max())

Missing dates: 0
Date type: datetime64[us]
Minimum date: 2026-01-01 00:00:00
Maximum date: 2026-12-06 00:00:00

Validate Customer IDs

In [273]:
print(
    "Invalid Customer IDs:",
    (~df["Customer_ID"].isin(
        customer_master["Customer_ID"]
    )).sum()
)

Invalid Customer IDs: 0

Validate Payment Mode

In [274]:
df["Payment_Mode"].value_counts(dropna=False)

Payment_Mode
Net Banking    1019
Debit Card     1015
UPI            1008
Credit Card     999
Cash            959
Name: count, dtype: int64

In [275]:
print(
    "Missing Payment Mode:",
    df["Payment_Mode"].isnull().sum()
)

Missing Payment Mode: 0

Remove Investigation Columns

In [276]:
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Customer_ID',
 'Customer_Name',
 'Product',
 'Category',
 'Quantity',
 'Unit_Price',
 'Cost_Price',
 'Discount',
 'City',
 'State',
 'Region',
 'Salesperson',
 'Payment_Mode',
 'Quantity_Missing',
 'Payment_Mode_Missing',
 'Invalid_Quantity',
 'Invalid_Discount',
 'Quantity_Outlier']

In [277]:
df = df.drop(
    columns=[
        "Quantity_Missing",
        "Payment_Mode_Missing",
        "Invalid_Quantity",
        "Invalid_Discount",
        "Quantity_Outlier"
    ]
)

In [278]:
df.shape

(5000, 15)

Final Data Quality Check

In [279]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Invalid quantities:", (df["Quantity"] <= 0).sum())
print("Invalid discounts:",
      ((df["Discount"] < 0) | (df["Discount"] > 100)).sum())
print("Invalid customer IDs:",
      (~df["Customer_ID"].isin(
          customer_master["Customer_ID"]
      )).sum())
print("Price below cost:",
      (df["Unit_Price"] < df["Cost_Price"]).sum())

Rows: 5000
Columns: 15
Missing values: 0
Duplicate rows: 0
Invalid quantities: 0
Invalid discounts: 0
Invalid customer IDs: 0
Price below cost: 0

Saving this cleaned dataset

In [280]:
df.to_csv(
    "../data/clean_sales_data.csv",
    index=False
)

In [292]:
clean_df = pd.read_csv("../data/clean_sales_data.csv")

print("Rows:", len(clean_df))
print("Columns:", len(clean_df.columns))
print("Missing values:", clean_df.isnull().sum().sum())
print("Duplicate rows:", clean_df.duplicated().sum())
print("Invalid quantities:", (clean_df["Quantity"] <= 0).sum())
print("Invalid discounts:", (clean_df["Discount"] < 0).sum() + (clean_df["Discount"] > 100).sum())

Rows: 5000
Columns: 15
Missing values: 0
Duplicate rows: 0
Invalid quantities: 0
Invalid discounts: 0

In [293]:
print("Columns:")
print(clean_df.columns.tolist())

Columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Cost_Price', 'Discount', 'City', 'State', 'Region', 'Salesperson', 'Payment_Mode']

In [294]:
print(clean_df.head())

  Order_ID  Order_Date Customer_ID  Customer_Name       Product     Category  \
0  ORD3526  2026-03-04       C0223   Sneha Mishra  Office Chair    Furniture
1  ORD3923  2026-03-01       C0212  Karan Agarwal      Notebook   Stationery
2  ORD1890  2026-06-24       C0015    Rahul Yadav    Smartphone  Electronics
3  ORD1658  2026-08-02       C0467   Kavita Singh      Notebook   Stationery
4  ORD5317  2026-02-06       C0979    Ravi Sharma  Office Chair    Furniture

   Quantity  Unit_Price  Cost_Price  Discount       City          State  \
0       2.0     12000.0        8500      10.0  Gorakhpur  Uttar Pradesh
1       1.0       120.0          65      10.0      Delhi          Delhi
2       1.0     28000.0       22000       0.0      Delhi          Delhi
3       5.0       120.0          65      10.0    Kolkata    West Bengal
4       4.0     12000.0        8500      20.0     Jaipur      Rajasthan

  Region Salesperson Payment_Mode
0  North       Sneha          UPI
1  North       Priya   Debit Card
2  North        Neha          UPI
3   East        Neha  Net Banking
4  North       Karan  Net Banking