In [1]:
import os

gemini_key = os.getenv("GEMINI_API_KEY")

print("Gemini API key found:", gemini_key is not None)

Gemini API key found: True

In [2]:
from google import genai

client = genai.Client()

print("Gemini client created successfully.")

Gemini client created successfully.

In [3]:
from google.genai import types

response = client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents="Explain sales analytics in one simple sentence.",
    config=types.GenerateContentConfig(
        automatic_function_calling=types.AutomaticFunctionCallingConfig(
            disable=True
        )
    )
)

print(response.text)

Sales analytics is the practice of reviewing past data to help businesses predict trends, understand customer behavior, and close more deals.

"Don't automatically try to call functions. Just answer my question."

In [4]:
automatic_function_calling=types.AutomaticFunctionCallingConfig(
    disable=True
)

In [5]:
import json

with open("../data/business_summary.json", "r") as file:
    business_summary = json.load(file)

business_summary

{'total_orders': 5000,
 'total_units': 20103,
 'gross_revenue': 296176220.0,
 'net_revenue': 267607482.5,
 'total_cost': 229533135.0,
 'net_profit': 38074347.5,
 'net_profit_margin': 14.227684197881127,
 'average_net_order_value': 53521.4965,
 'best_product': 'Laptop',
 'best_product_revenue': 111683693.0,
 'best_product_profit': 10994103.0,
 'best_category': 'Electronics',
 'best_region': 'North',
 'best_salesperson': 'Priya',
 'best_customer': 'Rohan Saxena'}

# AI Sales Analyst

## Initial Business Analysis

In [6]:
prompt = f"""
You are a professional sales analyst.

Analyze the following sales business summary.

Business data:
{business_summary}

Provide:
1. Overall business performance
2. Biggest strengths
3. Important risks or concerns
4. Key opportunities
5. Three actionable recommendations

Use the actual numbers provided.
Do not invent information.
Keep the analysis clear and suitable for a business manager.
"""

In [7]:
response = client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents=prompt
)

print(response.text)

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

Here is the professional sales analysis based on the provided business summary:

### 1. Overall Business Performance
The business demonstrates a strong financial scale with a **gross revenue of $296,176,220.00** and a **net revenue of $267,607,482.50** across **5,000 total orders** (totaling 20,103 units sold).
* **Profitability:** After accounting for total costs of $229,533,135.00, the business generated a **net profit of $38,074,347.50**, resulting in a healthy **net profit margin of 14.23%**.
* **Order Value:** The average net order value stands at a robust **$53,521.50**, indicating high-value B2B transactions or premium product sales.

### 2. Biggest Strengths
* **High-Value Product Line:** The **Electronics** category and specifically the **Laptop** product line are dominant revenue drivers. Laptops alone generated **$111,683,693.00** in revenue (approximately 37.7% of gross revenue) and **$10,994,103.00** in profit.
* **Top-Performing Talent:** **Priya** is identified as the best-performing salesperson, directly contributing to this high-volume sales environment.
* **Key Accounts:** **Rohan Saxena** stands out as the top customer, showing the value of nurturing high-net-worth client relationships.
* **Geographic Success:** The **North** region is the leading market territory.

### 3. Important Risks or Concerns
* **Revenue Concentration:** A massive portion of total revenue ($111.68M out of $296.1M) relies on a single product type (Laptops). Any supply chain disruption, obsolescence, or aggressive pricing pressure in the Laptop market could severely impact overall profitability.
* **Cost Structure:** Total costs represent **85.77%** of net revenue ($229,533,135.00 cost against $267,607,482.50 net revenue), leaving a relatively tight margin for error against inflationary pressures or rising operational expenses.
* **Customer/Salesperson Dependency:** Heavy reliance on top individual assets like Rohan Saxena and Priya creates key-person and key-account vulnerabilities.

### 4. Key Opportunities
* **Cross-Selling & Upselling:** With an already high average net order value of **$53,521.50**, there is an opportunity to bundle accessories, software, or maintenance contracts with top-selling Laptops to further boost margins.
* **Geographic Expansion:** Replicating the sales strategies and success achieved in the **North** region across other underperforming or unexplored regions.
* **Workforce Enablement:** Analyzing Priya's sales techniques and applying them to train other sales representatives to elevate the baseline performance of the broader sales team.

### 5. Three Actionable Recommendations
1. **Diversify Product Marketing:** While protecting the Laptop and Electronics category, actively promote secondary product lines to reduce product concentration risk and protect the business from market shifts in PC hardware.
2. **Implement Key Account Management (KAM):** Assign a dedicated retention and growth strategy around top customers like Rohan Saxena, while setting up formal risk-mitigation protocols to safeguard the relationship.
3. **Conduct Vendor and Cost Audits:** Given that total costs consume over 85% of net revenue, negotiate better bulk-purchase terms with suppliers of high-demand items (like Laptops) to improve the current 14.23% net profit margin.

# Interactive AI Sales Analyst

In [8]:
question = input("Ask your sales question: ")

print("Your question:", question)

Your question: give me the insights

In [9]:
prompt = f"""
You are an AI Sales Analyst.

You are given the following verified sales analysis:

{business_summary}

The user has asked:

{question}

Answer the user's question using ONLY the provided business data.

Rules:
- Do not invent numbers.
- Use actual numbers from the data when relevant.
- Explain the reasoning clearly.
- Give a concise business recommendation when appropriate.
"""

print(prompt)

You are an AI Sales Analyst.

You are given the following verified sales analysis:

{'total_orders': 5000, 'total_units': 20103, 'gross_revenue': 296176220.0, 'net_revenue': 267607482.5, 'total_cost': 229533135.0, 'net_profit': 38074347.5, 'net_profit_margin': 14.227684197881127, 'average_net_order_value': 53521.4965, 'best_product': 'Laptop', 'best_product_revenue': 111683693.0, 'best_product_profit': 10994103.0, 'best_category': 'Electronics', 'best_region': 'North', 'best_salesperson': 'Priya', 'best_customer': 'Rohan Saxena'}

The user has asked:

give me the insights

Answer the user's question using ONLY the provided business data.

Rules:
- Do not invent numbers.
- Use actual numbers from the data when relevant.
- Explain the reasoning clearly.
- Give a concise business recommendation when appropriate.

In [10]:
response = client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents=prompt
)

print(response.text)

Based on the verified sales analysis provided, here are the key business insights:

### **Key Financial Performance**
* **Profitability:** The business generated **$267,607,482.50 in net revenue** across 5,000 orders (averaging **$53,521.50 per net order**). Total costs amounted to **$229,533,135.00**, resulting in a healthy **net profit of $38,074,347.50** and a **net profit margin of 14.23%**.
* **Volume:** A total of **20,103 units** were sold, averaging approximately 4 units per order.

### **Top Drivers of Success**
* **Best-Selling Product:** The **Laptop** is the star product, bringing in **$111,683,693.00 in revenue** and contributing **$10,994,103.00 in profit**. This indicates that high-value electronics are the primary engine for both top-line growth and bottom-line profit.
* **Top Category:** **Electronics** is the leading product category, aligning with the success of the Laptop.
* **Top Region:** The **North** region is the highest-performing geographic market.
* **Top Salesperson:** **Priya** is the leading sales performer, driving significant value for the team.
* **Top Customer:** **Rohan Saxena** is the most valuable individual customer by purchasing volume/value.

---

### **Business Recommendation**
* **Double Down on High-Value Assets:** Since Laptops and the Electronics category drive the bulk of the revenue and profit, allocate more marketing budget and inventory toward this product line.
* **Replicate Top-Tier Strategies:** Analyze Priya’s sales techniques in the North region and share those best practices across the broader sales team to lift performance in other regions. Additionally, consider loyalty or VIP engagement programs for top-tier clients like Rohan Saxena to secure repeat high-value orders.

## Sales Data Connection

Load the clean dataset

In [11]:
import pandas as pd

df = pd.read_csv("../data/clean_sales_data.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))

Rows: 5000
Columns: 15

In [12]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Product,Category,Quantity,Unit_Price,Cost_Price,Discount,City,State,Region,Salesperson,Payment_Mode
0,ORD3526,2026-03-04,C0223,Sneha Mishra,Office Chair,Furniture,2.0,12000.0,8500,10.0,Gorakhpur,Uttar Pradesh,North,Sneha,UPI
1,ORD3923,2026-03-01,C0212,Karan Agarwal,Notebook,Stationery,1.0,120.0,65,10.0,Delhi,Delhi,North,Priya,Debit Card
2,ORD1890,2026-06-24,C0015,Rahul Yadav,Smartphone,Electronics,1.0,28000.0,22000,0.0,Delhi,Delhi,North,Neha,UPI
3,ORD1658,2026-08-02,C0467,Kavita Singh,Notebook,Stationery,5.0,120.0,65,10.0,Kolkata,West Bengal,East,Neha,Net Banking
4,ORD5317,2026-02-06,C0979,Ravi Sharma,Office Chair,Furniture,4.0,12000.0,8500,20.0,Jaipur,Rajasthan,North,Karan,Net Banking

In [13]:
region_sales = (
    df.groupby("Region")["Unit_Price"]
      .sum()
      .sort_values(ascending=False)
)

region_sales

Region
North    23898060.0
South    19121140.0
West     17842030.0
East     12037660.0
Name: Unit_Price, dtype: float64

Revenue

In [14]:
df["Gross_Revenue"] = df["Quantity"] * df["Unit_Price"]

Regional revenue

In [15]:
region_sales = (
    df.groupby("Region")["Gross_Revenue"]
      .sum()
      .sort_values(ascending=False)
)

region_sales

Region
North    98173450.0
South    75894180.0
West     71716250.0
East     50392340.0
Name: Gross_Revenue, dtype: float64

Best region

In [16]:
best_region = region_sales.idxmax()
best_region_revenue = region_sales.max()

print("Best Region:", best_region)
print("Revenue:", round(best_region_revenue, 2))

Best Region: North
Revenue: 98173450.0

In [17]:
region_result = f"""
Best Region: {best_region}
Gross Revenue: ₹{best_region_revenue:,.2f}
"""

Asking Gemini to explain it

In [18]:
region_prompt = f"""
You are a professional sales analyst.

Python has calculated the following verified result:

{region_result}

Explain this result to a business manager.

Include:
1. Which region performed best
2. Its revenue
3. What this could mean for the business
4. One practical recommendation

Do not invent any additional numbers.
Clearly distinguish between verified data and business interpretation.
"""

In [19]:
response = client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents=region_prompt
)

print(response.text)

Here is the sales analysis based on the verified data provided by the Python calculation.

### 1. Verified Data

*   **Best Performing Region:** North
*   **Gross Revenue:** ₹98,173,450.00

---

### 2. Business Interpretation

*   **What this means for the business:**
    The North region is currently our primary revenue driver. Generating over ₹9.8 crore indicates that our product-market fit, pricing strategy, customer demand, and potentially our sales team's execution are strongest in this geographical area. It suggests a high concentration of active customers, effective market penetration, or larger average deal sizes compared to our other regions.

*   **One practical recommendation:**
    Conduct a comprehensive performance audit of the North region to identify *why* it is succeeding, and reallocate a portion of marketing and sales resources to replicate these successful strategies in our underperforming regions.

### Creating a reusable function

In [20]:
def ask_gemini(prompt):
    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )
    
    return response.text

In [21]:
answer = ask_gemini(region_prompt)

print(answer)

Here is the sales analysis based on the verified data provided:

### **Verified Data**
* **Best Performing Region:** North
* **Gross Revenue:** ₹98,173,450.00

---

### **Business Interpretation**
* **What this means for the business:**
  The North region is currently our primary revenue driver, significantly outpacing other territories. This indicates strong market penetration, effective regional sales execution, high customer demand, or potentially a larger addressable market in the North compared to the rest of the business footprint.

* **Practical Recommendation:**
  Conduct a best-practice review of the North region to identify the key drivers behind its success—such as specific sales strategies, high-performing product lines, or effective distribution channels—and evaluate how these tactics can be adapted and applied to underperforming regions.

## Product Analysis

Calculate Net Revenue

In [22]:
df["Net_Revenue"] = (
    df["Quantity"]
    * df["Unit_Price"]
    * (1 - df["Discount"] / 100)
)

Calculate Cost

In [23]:
df["Total_Cost"] = df["Quantity"] * df["Cost_Price"]

Calculate Profit

In [24]:
df["Profit"] = df["Net_Revenue"] - df["Total_Cost"]

Creating Product Analysis

In [25]:
product_analysis = (
    df.groupby("Product")
      .agg(
          Orders=("Order_ID", "count"),
          Units_Sold=("Quantity", "sum"),
          Gross_Revenue=("Gross_Revenue", "sum"),
          Net_Revenue=("Net_Revenue", "sum"),
          Profit=("Profit", "sum")
      )
)

Calculate Profit Margin

In [26]:
product_analysis["Profit_Margin"] = (
    product_analysis["Profit"]
    / product_analysis["Net_Revenue"]
    * 100
)
product_analysis = product_analysis.sort_values(
    "Net_Revenue",
    ascending=False
)

In [27]:
product_analysis

,Orders,Units_Sold,Gross_Revenue,Net_Revenue,Profit,Profit_Margin
Product,,,,,,
Laptop,584,2428.0,123265350.0,111683693.0,10994103.0,9.843964
Smartphone,476,1914.0,53619000.0,48437800.0,6329800.0,13.067893
Monitor,493,1970.0,35460000.0,31947300.0,4367300.0,13.670326
Printer,461,1886.0,30371000.0,27379050.0,3804050.0,13.894018
Office Chair,517,2029.0,24477000.0,22022100.0,4775600.0,21.685489
Desk,463,1817.0,16353000.0,14779350.0,3513950.0,23.776079
Headphones,517,2036.0,7126000.0,6412875.0,1933675.0,30.153012
Keyboard,500,1980.0,3830000.0,3486290.0,1308290.0,37.526712
Pen Set,480,1982.0,878750.0,788912.5,511432.5,64.827532
Notebook,509,2061.0,796120.0,670112.0,536147.0,80.008566

Top 5 Products

In [28]:
top_5_products = product_analysis.head(5)

top_5_products

,Orders,Units_Sold,Gross_Revenue,Net_Revenue,Profit,Profit_Margin
Product,,,,,,
Laptop,584,2428.0,123265350.0,111683693.0,10994103.0,9.843964
Smartphone,476,1914.0,53619000.0,48437800.0,6329800.0,13.067893
Monitor,493,1970.0,35460000.0,31947300.0,4367300.0,13.670326
Printer,461,1886.0,30371000.0,27379050.0,3804050.0,13.894018
Office Chair,517,2029.0,24477000.0,22022100.0,4775600.0,21.685489

Giving the table to Gemini

In [29]:
product_data = top_5_products.to_string()

In [30]:
product_prompt = f"""
You are a professional sales analyst.

Here is verified product-level sales data calculated by Python:

{product_data}

Analyze the product performance.

Explain:
1. Which products are strongest
2. Which products generate the most revenue
3. Which products generate the most profit
4. Any important profitability concern
5. Three practical recommendations

Use only the provided data.
Do not invent numbers.
"""

In [31]:
product_ai_answer = ask_gemini(product_prompt)

print(product_ai_answer)

Based on the verified product-level sales data, here is the professional sales analysis:

### 1. Which Products Are Strongest?
**Laptop** is the strongest overall product in terms of transaction volume, demand, and sheer financial scale. It leads all categories by a wide margin, generating **584 orders** and **2,428 units sold**.

Beyond Laptops, **Office Chair** represents a strong secondary performer. It records the second-highest order count (**517 orders**) and unit sales (**2,029 units**), while also standing out as the most efficient profit generator in the lineup.

### 2. Which Products Generate the Most Revenue?
**Laptop** overwhelmingly generates the most revenue, dwarfing all other products:
* **Gross Revenue:** $123,265,350.00
* **Net Revenue:** $111,683,693.00

For context, the Laptop's Net Revenue is more than double that of the second-highest revenue generator, the **Smartphone** ($48,437,800.00 Net Revenue).

### 3. Which Products Generate the Most Profit?
**Laptop** generates the most total profit by a substantial margin, yielding **$10,994,103.00** in net profit.

The remaining products rank by profit as follows:
* **Office Chair:** $4,775,600.00
* **Monitor:** $4,367,300.00
* **Smartphone:** $6,329,800.00 (Second highest profit)
* **Printer:** $3,804,050.00

### 4. Any Important Profitability Concern?
There is an inverse relationship between revenue scale and profit margin that presents a notable concern for the **Laptop** category:
* While Laptops command **$111.68M** in net revenue and **$11M** in profit, their **Profit Margin is the lowest at 9.84%**.
* Conversely, **Office Chairs** generate the lowest net revenue ($22.02M) but boast the highest **Profit Margin at 21.69%**—more than double the margin of Laptops.

This indicates that Laptops are expensive to sell or produce relative to their return, carrying heavy overhead or discounting that compresses margins despite massive top-line volume.

### 5. Three Practical Recommendations
Based strictly on the provided data, here are three recommendations:

1. **Investigate and Optimize Laptop Cost Structures:** Because Laptops drive the vast majority of the company's revenue ($111.68M net) and total profit ($10.99M), even a minor percentage improvement to their 9.84% profit margin would yield massive dollar gains. Management should audit the costs associated with Laptops to protect or expand margins.
2. **Scale Marketing and Sales for Office Chairs:** Office Chairs demonstrate the strongest efficiency in the portfolio with a stellar **21.68% profit margin** and solid demand (517 orders / 2,029 units). Capital and promotional efforts should be directed here to increase unit volume, as they yield high returns relative to their revenue footprint.
3. **Re-evaluate Printers and Monitors:** Printers and Monitors occupy the middle-to-lower tiers across all metrics. Printers specifically generate the lowest net revenue ($27,379,050.00) and lowest profit ($3,804,050.00). Sales strategies for Printers and Monitors should be reviewed to either improve their 13% profit margins or shift focus to higher-margin items like Office Chairs.

## Category Performance Analysis

In [32]:
category_analysis = (
    df.groupby("Category")
      .agg(
          Orders=("Order_ID", "count"),
          Units_Sold=("Quantity", "sum"),
          Gross_Revenue=("Gross_Revenue", "sum"),
          Net_Revenue=("Net_Revenue", "sum"),
          Profit=("Profit", "sum")
      )
)

Profit Margin

In [33]:
category_analysis["Profit_Margin"] = (
    category_analysis["Profit"]
    / category_analysis["Net_Revenue"]
    * 100
)

In [34]:
category_analysis = category_analysis.sort_values(
    "Net_Revenue",
    ascending=False
)

category_analysis

,Orders,Units_Sold,Gross_Revenue,Net_Revenue,Profit,Profit_Margin
Category,,,,,,
Electronics,3041,12243.0,253770390.0,229434715.5,28755260.5,12.533090
Furniture,976,3838.0,40734000.0,36716250.0,8272350.0,22.530487
Stationery,983,4022.0,1671830.0,1456517.0,1046737.0,71.865759

Category Analysis by Gemini

In [35]:
category_data = category_analysis.to_string()

In [36]:
category_prompt = f"""
You are a professional sales analyst.

Analyze this verified category-level sales data calculated by Python:

{category_data}

Explain:

1. Which category performs best by revenue
2. Which category performs best by profit
3. Which category has the strongest profit margin
4. Any important business concern
5. Three practical recommendations

Use only the provided data.
Do not invent numbers.
"""

In [37]:
category_ai_answer = ask_gemini(category_prompt)

print(category_ai_answer)

Based on the verified category-level sales data provided, here is the professional sales analysis:

### 1. Best Performing Category by Revenue
**Electronics** performs best by revenue, generating a Gross Revenue of **$253,770,390.0** and a Net Revenue of **$229,434,715.5**. It dominates total sales volume, accounting for 12,243.0 units sold across 3,041 orders.

### 2. Best Performing Category by Profit
**Electronics** also performs best by profit, delivering **$28,755,260.5** in total profit.

### 3. Category with the Strongest Profit Margin
**Stationery** has by far the strongest profit margin at **71.87%** (71.865759%), far outpacing Furniture (22.53%) and Electronics (12.53%).

### 4. Important Business Concern
A critical concern is the **very low profit margin in the Electronics category (12.53%)**, despite its massive revenue share. Because Electronics generates the vast majority of the company's financial volume, even a slight compression in its margins, a rise in returns, or unexpected operational costs could severely impact the company's overall bottom line. Additionally, Stationery generates very low absolute revenue ($1,456,517.0 Net Revenue) despite its high margin, limiting its overall impact on company profits ($1,046,737.0).

### 5. Three Practical Recommendations
1. **Optimize Electronics Cost Structure:** Investigate the cost drivers in the Electronics category to see if supplier negotiations, pricing adjustments, or supply chain efficiencies can improve its 12.53% profit margin.
2. **Scale Stationery Marketing and Sales:** Capitalize on Stationery's exceptionally strong 71.87% profit margin by increasing sales volume and marketing efforts to drive higher absolute profit contribution from this category.
3. **Re-evaluate Furniture Strategy:** Assess Furniture's performance—which sits in the middle across orders (976), net revenue ($36,716,250.0), and profit margin (22.53%)—to determine if it can be scaled for higher profitability or if resources are better reallocated to Electronics and Stationery.

## Regional Performance Analysis

In [38]:
regional_analysis = (
    df.groupby("Region")
      .agg(
          Orders=("Order_ID", "count"),
          Units_Sold=("Quantity", "sum"),
          Gross_Revenue=("Gross_Revenue", "sum"),
          Net_Revenue=("Net_Revenue", "sum"),
          Profit=("Profit", "sum")
      )
)

In [39]:
regional_analysis["Profit_Margin"] = (
    regional_analysis["Profit"]
    / regional_analysis["Net_Revenue"]
    * 100
)

In [40]:
regional_analysis = regional_analysis.sort_values(
    "Net_Revenue",
    ascending=False
)

regional_analysis

,Orders,Units_Sold,Gross_Revenue,Net_Revenue,Profit,Profit_Margin
Region,,,,,,
North,1658,6739.0,98173450.0,88641741.5,12658576.5,14.280604
South,1288,5115.0,75894180.0,69072935.0,10255010.0,14.846640
West,1204,4827.0,71716250.0,64347450.0,8761665.0,13.616181
East,850,3422.0,50392340.0,45545356.0,6399096.0,14.049942

Best region

In [41]:
best_region = regional_analysis["Net_Revenue"].idxmax()

best_region_revenue = regional_analysis.loc[
    best_region, "Net_Revenue"
]

print("Best Region:", best_region)
print("Net Revenue:", round(best_region_revenue, 2))

Best Region: North
Net Revenue: 88641741.5

Region analysis with Gemini

In [42]:
regional_data = regional_analysis.to_string()

regional_prompt = f"""
You are a professional sales analyst.

Analyze the following verified regional sales data:

{regional_data}

Provide:

1. Best performing region
2. Lowest performing region
3. Revenue comparison
4. Profitability comparison
5. Important regional opportunity or risk
6. Three practical recommendations

Use only the provided data.
Do not invent numbers.
"""

regional_ai_answer = ask_gemini(regional_prompt)

print(regional_ai_answer)

Based on the verified regional sales data provided, here is the professional sales analysis:

### 1. Best Performing Region
* **North:** The North region is the top performer across all volume metrics, leading with **1,658 orders**, **6,739.0 units sold**, **$98,173,450.0 in gross revenue**, **$88,641,741.5 in net revenue**, and **$12,658,576.5 in profit**.

### 2. Lowest Performing Region
* **East:** The East region is the lowest performing region across all absolute volume metrics, recording **850 orders**, **3,422.0 units sold**, **$50,392,340.0 in gross revenue**, **$45,545,356.0 in net revenue**, and **$6,399,096.0 in profit**.

### 3. Revenue Comparison
* **North** leads significantly with $98.17M gross and $88.64M net revenue.
* **South** follows in second place with $75.89M gross and $69.07M net revenue.
* **West** ranks third with $71.72M gross and $64.35M net revenue.
* **East** trails all regions with $50.39M gross and $45.55M net revenue.
* *Note:* Gross-to-net revenue deductions are consistently proportional across all regions, hovering roughly between 9% and 10%.

### 4. Profitability Comparison
* **North** generates the highest absolute profit at **$12,658,576.5**.
* **South** generates the second-highest profit at **$10,255,010.0**, followed by the **West** at **$8,761,665.0**, and the **East** at **$6,399,096.0**.
* **Profit Margin Efficiency:** Interestingly, the **South** region achieves the highest profitability efficiency with a profit margin of **14.85%**, despite ranking second in total volume and revenue. The **North** follows closely at **14.28%**, the **East** at **14.05%**, and the **West** has the lowest margin at **13.62%**.

### 5. Important Regional Opportunity or Risk
* **Opportunity (South Region Efficiency):** The South region demonstrates strong margin performance (14.85%) relative to its volume, indicating effective cost control or favorable product mix that could serve as a benchmark for other regions.
* **Risk (West Region Margin Compression):** The West region underperforms in profit margin (13.62%) relative to its scale. Despite generating higher gross revenue ($71.72M) and unit sales (4,827) than the East ($50.39M and 3,422 units), the West yields a lower margin than the East (14.05%), indicating a risk of margin erosion or high operating costs in the West.

### 6. Three Practical Recommendations
1. **Investigate West Region Cost Structures:** Conduct an internal review of the West region to identify the drivers behind its lowest-in-class profit margin (13.62%) despite generating the third-highest revenue.
2. **Replicate South Region Practices:** Analyze the operational and pricing strategies used in the South region—which achieved the highest profit margin (14.85%)—and apply those best practices to the North and West regions to improve overall profitability.
3. **Scale East Region Volume:** Evaluate market penetration strategies for the East region. While its profit margin (14.05%) is healthy, its low order volume (850 orders) limits its total earnings contribution; increasing volume without sacrificing margin will drive higher absolute profit.

## Customer Performance Analysis

In [43]:
customer_analysis = (
    df.groupby(["Customer_ID", "Customer_Name"])
      .agg(
          Orders=("Order_ID", "count"),
          Units_Sold=("Quantity", "sum"),
          Net_Revenue=("Net_Revenue", "sum"),
          Profit=("Profit", "sum")
      )
)

Profit Margin

In [44]:
customer_analysis["Profit_Margin"] = (
    customer_analysis["Profit"]
    / customer_analysis["Net_Revenue"]
    * 100
)

In [45]:
customer_analysis = customer_analysis.sort_values(by=
    "Net_Revenue",
    ascending=False
)

Finding best customer

In [46]:
best_customer = customer_analysis.iloc[0]

print("Best Customer:", best_customer.name)
print("Revenue:", round(best_customer["Net_Revenue"], 2))
print("Profit:", round(best_customer["Profit"], 2))

Best Customer: ('C0373', 'Rohan Saxena')
Revenue: 1153065.0
Profit: 162960.0

Cutomer Analysis with Gemini

In [47]:
customer_data = customer_analysis.head(10).to_string()

In [48]:
customer_prompt = f"""
You are a professional sales analyst.

Analyze this verified top-customer data calculated by Python:

{customer_data}

Explain:

1. Which customers are most valuable
2. Which customers generate the most revenue
3. Which customers generate the most profit
4. Any customer concentration risk
5. Three practical customer-retention recommendations

Use only the provided data.
Do not invent numbers.
"""
customer_ai_answer = ask_gemini(customer_prompt)

print(customer_ai_answer)

Based on the verified top-customer data provided, here is the professional sales analysis:

### 1. Most Valuable Customers
Overall value combines purchasing frequency, volume, revenue generation, and profitability. Based on these metrics, the most valuable customers are:
* **Rohan Saxena (C0373):** Leads in net revenue ($1,153,065.0) and generates the highest profit ($162,960.0) with a healthy 14.13% profit margin across 9 orders.
* **Nisha Kumar (C0329):** Generates the second-highest profit ($161,550.0) and net revenue ($1,086,550.0) while maintaining the highest profit margin among the top tier at 14.87% across 8 orders.
* **Anjali Verma (C0508):** Strong all-around performer with 39 units sold, over $1M in net revenue ($1,038,375.0), and a solid profit of $139,575.0 (13.44% margin).

### 2. Customers Generating the Most Revenue
The top three customers generating the highest **Net Revenue** are:
1. **Rohan Saxena (C0373):** $1,153,065.0
2. **Nisha Kumar (C0329):** $1,086,550.0
3. **Manish Tiwari (C0695):** $1,061,630.0 *(Note: Despite high revenue, Manish Tiwari yields a lower profit of $90,530.0 due to an 8.53% margin).*

### 3. Customers Generating the Most Profit
The top three customers generating the highest **Profit** are:
1. **Rohan Saxena (C0373):** $162,960.0
2. **Nisha Kumar (C0329):** $161,550.0
3. **Anjali Verma (C0508):** $139,575.0

### 4. Customer Concentration Risk
There is a notable **negative margin/profitability risk** tied to specific accounts within this top tier rather than extreme top-line dependency:
* **Ravi Saxena (C0025):** Represents a critical operational and financial risk. Despite generating $891,954.0 in net revenue across 8 orders and 36 units sold, Ravi Saxena yields a **negative profit (-$2,436.0)** and a **negative profit margin (-0.27%)**. This indicates that high revenue does not equate to value if discounting, discounting structures, or fulfillment costs outpace revenue.
* **Margin Variance Risk:** There is significant volatility in profitability among high-revenue accounts. For instance, Nisha Kumar (C0332) generates $955,467.0 in revenue but yields only $54,172.0 in profit (a 5.67% margin), whereas Nisha Kumar (C0329) yields a 14.87% margin on slightly higher revenue.

### 5. Three Practical Customer-Retention Recommendations
1. **VIP Care and Loyalty Incentives for Rohan Saxena and Nisha Kumar (C0329):**
   As the dual leaders in both revenue and profit generation, these two accounts are vital to the bottom line. Implement dedicated account management, priority fulfillment, and volume-based loyalty perks to ensure they do not churn to competitors.
2. **Audit and Restructure Pricing for Ravi Saxena (C0025):**
   Stop treating Ravi Saxena as a top customer based solely on revenue. Conduct an immediate transaction audit to identify why this account is operating at a net loss (-$2,436.0). Adjust pricing, eliminate unprofitable discounting, or renegotiate terms before investing further retention efforts.
3. **Margin Optimization for Low-Margin High-Revenue Accounts (e.g., Nisha Kumar C0332 & Manish Tiwari C0695):**
   Review the product mix purchased by accounts like Manish Tiwari (8.53% margin) and Nisha Kumar C0332 (5.67% margin). Shift their purchasing focus toward higher-margin items or bundle products more strategically to bring their profitability closer to the top performers (who achieve 13% to 14%+ margins).

## Salesperson Performance Analysis

Calculate salesperson performance

In [49]:
salesperson_analysis = (
    df.groupby("Salesperson")
      .agg(
          Orders=("Order_ID", "count"),
          Units_Sold=("Quantity", "sum"),
          Net_Revenue=("Net_Revenue", "sum"),
          Profit=("Profit", "sum")
      )
)

Calculate profit margin

In [50]:
salesperson_analysis["Profit_Margin"] = (
    salesperson_analysis["Profit"]
    / salesperson_analysis["Net_Revenue"]
    * 100
)

Calculate profit margin

In [51]:
salesperson_analysis["Profit_Margin"] = (
    salesperson_analysis["Profit"]
    / salesperson_analysis["Net_Revenue"]
    * 100
)

Sort by revenue

In [52]:
salesperson_analysis = salesperson_analysis.sort_values(
    "Net_Revenue",
    ascending=False
)

salesperson_analysis

             Orders  Units_Sold  Net_Revenue     Profit  Profit_Margin
Salesperson
Priya           865      3441.0   49114230.5  6859290.5      13.965994
Sneha           865      3480.0   48901393.5  6996508.5      14.307381
Ravi            867      3441.0   48258785.0  6342710.0      13.143120
Amit            822      3267.0   41880763.5  6281933.5      14.999568
Neha            787      3168.0   40751767.5  5752162.5      14.115124
Karan           794      3306.0   38700542.5  5841742.5      15.094730

Find the best salesperson

In [53]:
best_salesperson = salesperson_analysis.iloc[0]

print("Best Salesperson:", best_salesperson.name)
print("Best Salesperson:", best_salesperson.name)
print("Revenue:", round(best_salesperson["Net_Revenue"], 2))
print("Profit:", round(best_salesperson["Profit"], 2))
print("Profit Margin:", round(best_salesperson["Profit_Margin"], 2), "%")
print("Profit:", round(best_salesperson["Profit"], 2))
print("Profit Margin:", round(best_salesperson["Profit_Margin"], 2), "%")

Best Salesperson: Priya
Best Salesperson: Priya
Revenue: 49114230.5
Profit: 6859290.5
Profit Margin: 13.97 %
Profit: 6859290.5
Profit Margin: 13.97 %

Gemini analysis for the salespeople

In [54]:
salesperson_data = salesperson_analysis.to_string()

salesperson_prompt = f"""
You are a professional sales analyst.

Analyze the following verified salesperson performance data:

{salesperson_data}

Explain:

1. Which salesperson performs best by revenue
2. Which salesperson generates the most profit
3. Which salesperson has the strongest profit margin
4. Any significant performance differences
5. Three practical recommendations for improving salesperson performance

Use only the provided data.
Do not invent numbers.
"""

salesperson_ai_answer = ask_gemini(salesperson_prompt)

print(salesperson_ai_answer)

Based on the verified salesperson performance data provided, here is the professional sales analysis:

### 1. Best Performer by Revenue
**Priya** is the top-performing salesperson by net revenue, generating **$49,114,230.5**. She narrowly outperforms Sneha, who generated $48,901,393.5 despite selling slightly more units.

### 2. Salesperson Generating the Most Profit
**Sneha** generates the most profit, delivering **$6,996,508.5**. She achieves this despite having the exact same order count as Priya (865 orders) and slightly lower net revenue, indicating a more profitable product mix or better pricing execution.

### 3. Salesperson with the Strongest Profit Margin
**Karan** has the strongest profit margin at **15.094730%** (followed very closely by Amit at 14.999568%). Karan achieves this high efficiency despite having the second-lowest order count (794) and the lowest total net revenue ($38,700,542.5) among the team.

### 4. Significant Performance Differences
* **Top-Tier vs. Lower-Tier Volume:** Priya, Sneha, and Ravi form a clear top tier in terms of order volume (865–867 orders), whereas Neha (787 orders) and Karan (794 orders) lag significantly behind in order acquisition.
* **Revenue Disconnect:** Karan generates the lowest net revenue ($38,700,542.5) but secures the highest profit margin (15.09%), showing that lower sales volume does not preclude high efficiency. Conversely, Ravi secures high order volume (867 orders) and high revenue ($48,258,785.0), but suffers from the lowest profit margin on the team at 13.143120%.
* **Margin Spread:** There is a distinct spread in profitability efficiency across the team, ranging from Ravi's low of 13.14% up to Karan's high of 15.09%.

### 5. Three Practical Recommendations for Improving Salesperson Performance
1. **Replicate Sneha and Karan's Margin Strategies:** Analyze the specific product mix, discounting practices, or pricing strategies used by Sneha (14.31% margin) and Karan (15.09% margin) and share these best practices with Ravi, whose margin lags at 13.14%.
2. **Targeted Sales Coaching for Neha and Karan:** Provide lead-generation and pipeline-expansion support to Neha (787 orders) and Karan (794 orders) to help them increase their order volume closer to the 860+ benchmark set by Priya, Sneha, and Ravi.
3. **Optimize Ravi's Profitability:** Since Ravi successfully drives high order volume (867) and high revenue ($48.2M), management should work with him to shift focus toward higher-margin products or reduce unnecessary discounting to improve his lowest-in-class profit margin of 13.14%.

## Profitability Analysis

In [55]:
profit_analysis = (
    df.groupby("Product")
      .agg(
          Net_Revenue=("Net_Revenue", "sum"),
          Total_Cost=("Total_Cost", "sum"),
          Profit=("Profit", "sum")
      )
)

Calculating Profit Margin

In [56]:
profit_analysis["Profit_Margin"] = (
    profit_analysis["Profit"]
    / profit_analysis["Net_Revenue"]
    * 100
)

In [57]:
profit_analysis = profit_analysis.sort_values(by= "Profit",
       ascending=False
)

profit_analysis

              Net_Revenue   Total_Cost      Profit  Profit_Margin
Product
Laptop        111683693.0  100689590.0  10994103.0       9.843964
Smartphone     48437800.0   42108000.0   6329800.0      13.067893
Office Chair   22022100.0   17246500.0   4775600.0      21.685489
Monitor        31947300.0   27580000.0   4367300.0      13.670326
Printer        27379050.0   23575000.0   3804050.0      13.894018
Desk           14779350.0   11265400.0   3513950.0      23.776079
Headphones      6412875.0    4479200.0   1933675.0      30.153012
Keyboard        3486290.0    2178000.0   1308290.0      37.526712
Notebook         670112.0     133965.0    536147.0      80.008566
Pen Set          788912.5     277480.0    511432.5      64.827532

most profitable product

In [58]:
most_profitable = profit_analysis.iloc[0]

print("Most Profitable Product:", most_profitable.name)
print("Profit:", round(most_profitable["Profit"], 2))
print("Profit Margin:", round(most_profitable["Profit_Margin"], 2), "%")

Most Profitable Product: Laptop
Profit: 10994103.0
Profit Margin: 9.84 %

lowest-profit product

In [59]:
least_profitable = profit_analysis.iloc[-1]

print("Least Profitable Product:", least_profitable.name)
print("Profit:", round(least_profitable["Profit"], 2))
print("Profit Margin:", round(least_profitable["Profit_Margin"], 2), "%")

Least Profitable Product: Pen Set
Profit: 511432.5
Profit Margin: 64.83 %

Gemini interpret profitability

In [60]:
profit_data = profit_analysis.to_string()

profit_prompt = f"""
You are a professional sales and profitability analyst.

Analyze the following verified product profitability data calculated by Python:

{profit_data}

Explain:

1. Which products generate the most profit
2. Which products have the strongest profit margins
3. Which products have weak profitability
4. Whether high revenue necessarily means high profit
5. Important profitability risks
6. Three practical recommendations to improve profit

Use only the provided data.
Do not invent numbers.
"""

profit_ai_answer = ask_gemini(profit_prompt)

print(profit_ai_answer)

Based on the verified product profitability data provided, here is the professional analysis:

### 1. Which products generate the most profit
Profit generation is led heavily by high-volume hardware, with **Laptops** generating by far the most total profit at **$10,994,103.0**. This is followed by **Smartphones** (**$6,329,800.0**) and **Office Chairs** (**$4,775,600.0**). Monitors, Printers, and Desks also contribute solid profits ranging between $3.5 million and $4.3 million.

### 2. Which products have the strongest profit margins
The strongest profit margins are found in low-cost, accessory, and stationery items:
* **Notebook:** **80.01%** profit margin ($536,147.0 profit on $670,112.0 revenue)
* **Pen Set:** **64.83%** profit margin ($511,432.5 profit on $788,912.5 revenue)
* **Keyboard:** **37.53%** profit margin ($1,308,290.0 profit on $3,486,290.0 revenue)
* **Headphones:** **30.15%** profit margin ($1,933,675.0 profit on $6,412,875.0 revenue)

### 3. Which products have weak profitability
While no products show a net loss, the lowest *total profit* generators are stationery and office supply items due to their small scale:
* **Pen Set:** **$511,432.5** total profit
* **Notebook:** **$536,147.0** total profit
* **Keyboard:** **$1,308,290.0** total profit
* **Headphones:** **$1,933,675.0** total profit

However, if "weak profitability" is viewed through the lens of *efficiency* (profit margin), the **Laptop** has the weakest profit margin by a wide margin at **9.84%**, despite generating the most total dollars.

### 4. Whether high revenue necessarily means high profit
**No, high revenue does not necessarily mean high profit.** This is most clearly demonstrated by the **Laptop**:
* It brings in the highest Net Revenue by far (**$111,683,693.0**), which is more than double the revenue of the second-place product (Smartphones at $48,437,800.0).
* However, because of its very high total cost ($100,689,590.0), its profit margin is compressed to **9.84%**, the lowest on the list.
* Conversely, items like **Notebooks** and **Pen Sets** generate very low revenues (under $800,000 each) but yield exceptionally high profit margins (over 64%).

### 5. Important profitability risks
* **Margin Compression on High-Volume Items:** Laptops represent the core revenue driver of the business but operate on a razor-thin 9.84% margin. Any unexpected increase in production, supply chain, or operational costs for laptops could severely wipe out the company's net profit.
* **Over-Reliance on Low-Margin Giants:** Because Laptops and Smartphones make up the bulk of total revenue and profit dollars, minor negative shifts in their sales volume or cost structures present an outsized risk to overall company health.
* **Low Volume Scale Risk:** High-margin items like Notebooks (80.01%) and Pen Sets (64.83%) have fantastic margins, but their total profit contribution is minimal ($536k and $511k, respectively) due to extremely low total revenue. They cannot currently carry the financial weight of the business if core hardware sales dip.

### 6. Three practical recommendations to improve profit
1. **Optimize Laptop Cost Structures:** Because Laptops generate the most total profit ($10.9M) but suffer from the lowest margin (9.84%), even a 1- or 2-percentage-point reduction in Total Cost ($100,689,590.0) would yield significant monetary gains in net profit.
2. **Scale Marketing and Distribution for High-Margin Products:** Increase sales volume for Notebooks and Pen Sets. Because they boast massive profit margins (80.01% and 64.83%), scaling their revenue will directly translate to high-return profit growth without requiring massive proportional cost increases.
3. **Review Mid-Tier Pricing and Costs:** Evaluate products in the middle tiers (such as Office Chairs at 21.69% and Desks at 23.78%) to see if slight price optimizations can be made, as they successfully balance decent revenue generation with healthy margins.

## Discount Analysis

In [61]:
discount_analysis = (
    df.groupby("Discount")
      .agg(
          Orders=("Order_ID", "count"),
          Net_Revenue=("Net_Revenue", "sum"),
          Profit=("Profit", "sum")
      )
      .sort_index()
)

discount_analysis

          Orders  Net_Revenue      Profit
Discount
0.0         1019   64928700.0  14434275.0
5.0         1012   57897702.5  10382457.5
10.0        1002   50667642.0   7441332.0
15.0         979   49457862.0   4274787.0
20.0         988   44655576.0   1541496.0

In [62]:
discount_analysis["Profit_Margin"] = (
    discount_analysis["Profit"]
    / discount_analysis["Net_Revenue"]
    * 100
)

discount_analysis

          Orders  Net_Revenue      Profit  Profit_Margin
Discount
0.0         1019   64928700.0  14434275.0      22.230963
5.0         1012   57897702.5  10382457.5      17.932417
10.0        1002   50667642.0   7441332.0      14.686557
15.0         979   49457862.0   4274787.0       8.643291
20.0         988   44655576.0   1541496.0       3.451968

Asking Gemini about discounts

In [63]:
discount_data = discount_analysis.to_string()

In [64]:
discount_prompt = f"""
You are a professional sales analyst.

Analyze the following verified discount-level performance data:

{discount_data}

Explain:

1. How discounts affect revenue
2. How discounts affect profit
3. Which discount levels appear risky
4. Whether higher discounts appear to reduce profitability
5. Three recommendations for discount strategy

Use only the provided data.
Do not claim causation unless the data supports it.
Do not invent numbers.
"""

discount_ai_answer = ask_gemini(discount_prompt)

print(discount_ai_answer)

Based on the verified discount-level performance data provided, here is the sales analysis:

### 1. How discounts affect revenue
As the discount level increases from 0.0 to 20.0, net revenue consistently decreases. At a 0.0 discount, the net revenue is at its peak of $64,928,700.0 across 1,019 orders. As discounts rise incrementally to 5.0, 10.0, 15.0, and finally 20.0, net revenue drops progressively, reaching its lowest point of $44,655,576.0 at the 20.0 discount level (despite a slight anomaly of 988 orders at 20.0 compared to 979 orders at 15.0).

### 2. How discounts affect profit
Profitability declines sharply as the discount level increases. At a 0.0 discount, profit is $14,434,275.0 with a profit margin of 22.23%. As discounts increase, profit drops at every single interval: falling to $10,382,457.5 at a 5.0 discount, $7,441,332.0 at 10.0, and $4,274,787.0 at 15.0, before plunging to a low of $1,541,496.0 at the 20.0 discount level. Concurrently, the profit margin decreases steadily from 22.23% down to 3.45%.

### 3. Which discount levels appear risky
The 15.0 and 20.0 discount levels appear particularly risky. At the 15.0 discount, the profit margin drops significantly into single digits at 8.64%, yielding $4,274,787.0 in profit from roughly the same volume of orders (979) as lower discount tiers. At the 20.0 discount level, the risk is severe: despite generating 988 orders (outperforming the 15.0 tier in order volume), the profit margin collapses to 3.45%, resulting in a minimal profit of just $1,541,496.0.

### 4. Whether higher discounts appear to reduce profitability
Yes, higher discounts clearly reduce profitability. The data shows an inverse relationship between discount levels and both total profit and profit margin. Moving from a 0.0 discount to a 20.0 discount causes total profit to drop by over 89% (from $14.43 million to $1.54 million) and slashes the profit margin from 22.23% to 3.45%, demonstrating that higher discounts erode financial returns.

### 5. Three recommendations for discount strategy
* **Limit or eliminate high-tier discounts:** Restrict or phase out the 15.0 and 20.0 discount levels, as their low profit margins (8.64% and 3.45% respectively) make them financially inefficient relative to the order volumes generated.
* **Prioritize low-to-zero discounting:** Focus sales and promotional strategies around the 0.0 discount level, which successfully captures the highest order volume (1,019) while delivering the maximum net revenue ($64,928,700.0) and highest profit margin (22.23%).
* **Reevaluate moderate discounting tiers:** Review the performance of the 5.0 and 10.0 discount levels to determine if they can be scaled back toward 0.0, given that profit margins continuously improve as the discount rate decreases.

## Monthly Sales Trend Analysis

In [65]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [66]:
df["Month"] = df["Order_Date"].dt.to_period("M")

Calculating monthly performance

In [67]:
monthly_analysis = (
    df.groupby("Month")
      .agg(
          Orders=("Order_ID", "count"),
          Units_Sold=("Quantity", "sum"),
          Net_Revenue=("Net_Revenue", "sum"),
          Profit=("Profit", "sum")
      )
)

Calculating monthly profit margin

In [68]:
monthly_analysis["Profit_Margin"] = (
    monthly_analysis["Profit"]
    / monthly_analysis["Net_Revenue"]
    * 100
)

monthly_analysis

         Orders  Units_Sold  Net_Revenue     Profit  Profit_Margin
Month
2026-01     636      2542.0   30452069.0  4436939.0      14.570238
2026-02     546      2196.0   30706878.5  4825958.5      15.716213
2026-03     668      2707.0   35241453.5  4731053.5      13.424683
2026-04     636      2588.0   36999743.0  5095673.0      13.772185
2026-05     662      2713.0   33254810.0  4685985.0      14.091150
2026-06     648      2536.0   33251292.0  5019262.0      15.094938
2026-07     614      2461.0   34954421.0  4383876.0      12.541693
2026-08     584      2340.0   32619609.5  4865049.5      14.914493
2026-09       1         4.0        432.0      172.0      39.814815
2026-12       5        16.0     126774.0    30379.0      23.963115

Best revenue month

In [69]:
best_month = monthly_analysis["Net_Revenue"].idxmax()

print("Best Revenue Month:", best_month)
print(
    "Revenue:",
    round(monthly_analysis.loc[best_month, "Net_Revenue"], 2)
)

Best Revenue Month: 2026-04
Revenue: 36999743.0

Best profit month

In [70]:
best_profit_month = monthly_analysis["Profit"].idxmax()

print("Best Profit Month:", best_profit_month)
print(
    "Profit:",
    round(monthly_analysis.loc[best_profit_month, "Profit"], 2)
)

Best Profit Month: 2026-04
Profit: 5095673.0

Lowest revenue month

In [71]:
worst_month = monthly_analysis["Net_Revenue"].idxmin()

print("Lowest Revenue Month:", worst_month)
print(
    "Revenue:",
    round(monthly_analysis.loc[worst_month, "Net_Revenue"], 2)
)

Lowest Revenue Month: 2026-09
Revenue: 432.0

Gemini analysis of the trend

In [72]:
monthly_data = monthly_analysis.to_string()

monthly_prompt = f"""
You are a professional sales analyst.

Analyze the following verified monthly sales data calculated by Python:

{monthly_data}

Explain:

1. Overall sales trend
2. Best revenue month
3. Best profit month
4. Weakest month
5. Any noticeable changes in profitability
6. Possible business implications
7. Three practical recommendations

Use only the provided data.
Do not invent numbers.
Do not claim seasonality unless the data provides enough evidence.
"""

monthly_ai_answer = ask_gemini(monthly_prompt)

print(monthly_ai_answer)

Based on the verified monthly sales data provided, here is the professional sales analysis:

### 1. Overall Sales Trend
The data reflects active business operations from January through August 2026, followed by a severe and sudden drop in activity during September 2026, and minimal residual activity in December 2026.
* Between **January and August**, business metrics remained relatively stable, with monthly orders ranging from 546 to 668, units sold between 2,196 and 2,713, and net revenues fluctuating consistently between roughly $30.4 million and $37.0 million.
* After August, operations collapsed. September recorded only 1 order and 4 units sold, and December recorded only 5 orders and 16 units sold. October and November are entirely absent from the dataset.

### 2. Best Revenue Month
* **April 2026** is the best revenue month, generating **$36,999,743.0** in Net Revenue (alongside 636 orders and 2,588 units sold).
* March 2026 was the second-highest revenue month at $35,241,453.5.

### 3. Best Profit Month
* **April 2026** is also the best profit month, yielding **$5,095,673.0** in Profit.
* June 2026 was a close second, generating $5,019,262.0 in profit despite having slightly lower net revenue than April.

### 4. Weakest Month
* **September 2026** is the weakest operating month by a wide margin, recording just **1 order**, **4.0 units sold**, **$432.0 in net revenue**, and **$172.0 in profit**.
* *(Note: While December has lower order counts than the early-year months, September represents the lowest active trading volume in the dataset).*

### 5. Any Noticeable Changes in Profitability
* **Consistency in the Active Period (Jan–Aug):** During the active months, the Profit Margin remained relatively stable, fluctuating in a narrow band between **12.54%** (July) and **15.72%** (February).
* **Anomalies in Low-Volume Months:** In the low-volume months of September and December, the profit margins spiked significantly to **39.81%** and **23.96%**, respectively. This suggests that the few transactions that did occur during these periods had a much higher margin profile, or that fixed costs/operational overhead were absent.

### 6. Possible Business Implications
* **Operational Disruption or Closure:** The abrupt drop from hundreds of orders per month (averaging over 600 orders/month from Jan–Aug) down to a single order in September strongly implies a critical business disruption, such as a major supply chain failure, loss of core contracts, loss of operating licenses, or a business suspension.
* **Data Gaps:** The complete absence of October and November data, followed by negligible activity in December, suggests the business was either non-operational during those months or data was unrecorded/lost.
* **Pricing/Product Mix Shift:** The high profit margins in September (39.8%) and December (23.9%) indicate that whatever few sales were made were high-margin items, custom orders, or liquidations, contrasting with the core high-volume product lines.

### 7. Three Practical Recommendations
1. **Investigate the Q3 Operational Collapse:** Management must immediately audit why order volume fell off a cliff after August 2026 to determine if the causes (e.g., vendor issues, platform outages, or legal/operational hurdles) can be resolved.
2. **Replicate April's Success Factors:** Analyze the product mix, pricing strategy, and marketing efforts from April 2026—which yielded both peak revenue and peak profit—to understand what drove optimal performance during that period.
3. **Examine High-Margin Outliers:** Review the specific transactions from September and December to see if the high profit margins (39.8% and 24.0%) can be leveraged as a niche or scaled product line once regular business operations resume.

## AI Analysis Data Package

In [73]:
ai_analysis_data = {
    "business_summary": business_summary,

    "top_products": (
        product_analysis
        .head(5)
        .round(2)
        .reset_index()
        .to_dict(orient="records")
    ),

    "categories": (
        category_analysis
        .round(2)
        .reset_index()
        .to_dict(orient="records")
    ),

    "regions": (
        regional_analysis
        .round(2)
        .reset_index()
        .to_dict(orient="records")
    ),

    "top_customers": (
        customer_analysis
        .head(10)
        .round(2)
        .reset_index()
        .to_dict(orient="records")
    ),

    "salespeople": (
        salesperson_analysis
        .round(2)
        .reset_index()
        .to_dict(orient="records")
    ),

    "profitability": (
        profit_analysis
        .round(2)
        .reset_index()
        .to_dict(orient="records")
    ),

    "discount_analysis": (
        discount_analysis
        .round(2)
        .reset_index()
        .to_dict(orient="records")
    ),

    "monthly_trends": (
        monthly_analysis
        .round(2)
        .reset_index()
        .astype({"Month": str})
        .to_dict(orient="records")
    )
}

Save the AI analysis package

In [74]:
import json

with open("../data/ai_analysis_data.json", "w") as file:
    json.dump(ai_analysis_data, file, indent=4, default=str)

print("AI analysis data saved successfully.")

AI analysis data saved successfully.

In [75]:
with open("../data/ai_analysis_data.json", "r") as file:
    test_data = json.load(file)

print("JSON loaded successfully.")
print(test_data.keys())

JSON loaded successfully.
dict_keys(['business_summary', 'top_products', 'categories', 'regions', 'top_customers', 'salespeople', 'profitability', 'discount_analysis', 'monthly_trends'])

# Final Interactive AI Sales Analyst

In [91]:
question = input("Ask your sales question: ")

print("Question:", question)

Question: Which region performs best?

Create a simple data selector

In [92]:
def select_analysis(question):
    question = question.lower()

    if "product" in question:
        return "Product Analysis", ai_analysis_data["top_products"]

    elif "category" in question:
        return "Category Analysis", ai_analysis_data["categories"]

    elif "region" in question:
        return "Regional Analysis", ai_analysis_data["regions"]

    elif "customer" in question:
        return "Customer Analysis", ai_analysis_data["top_customers"]

    elif "salesperson" in question:
        return "Salesperson Analysis", ai_analysis_data["salespeople"]

    elif "discount" in question:
        return "Discount Analysis", ai_analysis_data["discount_analysis"]

    elif "month" in question or "monthly" in question or "trend" in question:
        return "Monthly Analysis", ai_analysis_data["monthly_trends"]

    elif "profit" in question or "margin" in question:
        return "Profitability Analysis", ai_analysis_data["profitability"]

    else:
        return "Business Summary", ai_analysis_data["business_summary"]

Test the selector

In [93]:
analysis_name, analysis_data = select_analysis(question)

print("Selected Analysis:", analysis_name)
print("Data:")
print(analysis_data)

Selected Analysis: Regional Analysis
Data:
[{'Region': 'North', 'Orders': 1658, 'Units_Sold': 6739.0, 'Gross_Revenue': 98173450.0, 'Net_Revenue': 88641741.5, 'Profit': 12658576.5, 'Profit_Margin': 14.28}, {'Region': 'South', 'Orders': 1288, 'Units_Sold': 5115.0, 'Gross_Revenue': 75894180.0, 'Net_Revenue': 69072935.0, 'Profit': 10255010.0, 'Profit_Margin': 14.85}, {'Region': 'West', 'Orders': 1204, 'Units_Sold': 4827.0, 'Gross_Revenue': 71716250.0, 'Net_Revenue': 64347450.0, 'Profit': 8761665.0, 'Profit_Margin': 13.62}, {'Region': 'East', 'Orders': 850, 'Units_Sold': 3422.0, 'Gross_Revenue': 50392340.0, 'Net_Revenue': 45545356.0, 'Profit': 6399096.0, 'Profit_Margin': 14.05}]

Send the selected data to Gemini

In [94]:
final_prompt = f"""
You are an AI Sales Analyst for a business.

The following information was calculated and verified by Python:

Analysis Type: {analysis_name}
Verified Data: {analysis_data}
User Question: {question}

Answer the user's question as a professional business analyst.

Rules:
- Use only the provided verified data.
- Do not invent numbers.
- Clearly mention relevant numbers when available.
- Explain the business meaning.
- Give practical recommendations when appropriate.
- Keep the answer concise and easy for a business manager to understand.
"""

print(final_prompt)

You are an AI Sales Analyst for a business.

The following information was calculated and verified by Python:

Analysis Type: Regional Analysis
Verified Data: [{'Region': 'North', 'Orders': 1658, 'Units_Sold': 6739.0, 'Gross_Revenue': 98173450.0, 'Net_Revenue': 88641741.5, 'Profit': 12658576.5, 'Profit_Margin': 14.28}, {'Region': 'South', 'Orders': 1288, 'Units_Sold': 5115.0, 'Gross_Revenue': 75894180.0, 'Net_Revenue': 69072935.0, 'Profit': 10255010.0, 'Profit_Margin': 14.85}, {'Region': 'West', 'Orders': 1204, 'Units_Sold': 4827.0, 'Gross_Revenue': 71716250.0, 'Net_Revenue': 64347450.0, 'Profit': 8761665.0, 'Profit_Margin': 13.62}, {'Region': 'East', 'Orders': 850, 'Units_Sold': 3422.0, 'Gross_Revenue': 50392340.0, 'Net_Revenue': 45545356.0, 'Profit': 6399096.0, 'Profit_Margin': 14.05}]
User Question: Which region performs best?

Answer the user's question as a professional business analyst.

Rules:
- Use only the provided verified data.
- Do not invent numbers.
- Clearly mention relevant numbers when available.
- Explain the business meaning.
- Give practical recommendations when appropriate.
- Keep the answer concise and easy for a business manager to understand.

Ask Gemini

In [95]:
answer = ask_gemini(final_prompt)

print("\nAI SALES ANALYST")
print("=" * 100)
print(answer)

AI SALES ANALYST
====================================================================================================
Based on the verified data, the **North region** is the overall best-performing region across nearly all key sales and financial metrics.

### Key Performance Highlights for the North Region:
* **Order Volume:** Highest sales engagement with **1,658 orders** (significantly ahead of the South at 1,288, West at 1,204, and East at 850).
* **Volume Output:** Highest market penetration, moving **6,739 units sold**.
* **Revenue Generation:** Generated the highest **Gross Revenue of $98,173,450.00** and **Net Revenue of $88,641,741.50**.
* **Total Profit:** Delivered the highest raw **Profit of $12,658,576.50**.

*(Note: While the South region holds a slightly higher Profit Margin of 14.85% compared to the North's 14.28%, the North’s superior volume drives significantly higher total financial returns.)*

### Business Recommendations:
1. **Analyze Success Factors:** Investigate what is driving the high order volume and customer acquisition in the North (e.g., specific product mix, marketing campaigns, or strong sales representation) to see if these strategies can be replicated in lagging regions like the East.
2. **Optimize Profitability in the North:** Because the North's profit margin (14.28%) sits slightly below the South's (14.85%), leadership should review operational or discounting costs in the North to capture even more bottom-line value from its high revenue stream.

## Multi-Factor Analysis Engine

In [96]:
def select_multiple_analyses(question):
    question = question.lower()

    selected = {}

    if "product" in question:
        selected["Product Analysis"] = ai_analysis_data["top_products"]

    if "category" in question:
        selected["Category Analysis"] = ai_analysis_data["categories"]

    if "region" in question:
        selected["Regional Analysis"] = ai_analysis_data["regions"]

    if "customer" in question:
        selected["Customer Analysis"] = ai_analysis_data["top_customers"]

    if "salesperson" in question:
        selected["Salesperson Analysis"] = ai_analysis_data["salespeople"]

    if "discount" in question:
        selected["Discount Analysis"] = ai_analysis_data["discount_analysis"]

    if (
        "month" in question
        or "monthly" in question
        or "trend" in question
        or "sales increased" in question
        or "sales decreased" in question
    ):
        selected["Monthly Analysis"] = ai_analysis_data["monthly_trends"]

    if (
        "profit" in question
        or "margin" in question
        or "profitable" in question
    ):
        selected["Profitability Analysis"] = ai_analysis_data["profitability"]

    if len(selected) == 0:
        selected["Business Summary"] = ai_analysis_data["business_summary"]

    return selected

In [103]:
question = input("Ask your sales question: ")

selected_analyses = select_multiple_analyses(question)

print(selected_analyses.keys())

dict_keys(['Salesperson Analysis'])

Send multiple analyses to Gemini

In [104]:
analysis_text = str(selected_analyses)

final_prompt = f"""
You are a professional AI Sales Analyst.

The following information was calculated and verified by Python:

{analysis_text}

User Question:
{question}

Analyze the question using the relevant verified data.

Rules:
- Use only the provided data.
- Do not invent numbers.
- Explain the reasoning clearly.
- Connect information from multiple analyses when relevant.
- Distinguish facts from possible business interpretations.
- Give practical recommendations when appropriate.
- Keep the answer concise and suitable for a business manager.
"""

In [105]:
answer = ask_gemini(final_prompt)

print("\nAI SALES ANALYST")
print("=" * 50)
print(answer)

AI SALES ANALYST
==================================================
Based on the verified sales data, management should not rely on a single salesperson for a reward, as **Sneha** and **Priya** lead in different, equally critical performance categories.

Here is the comparative analysis to guide management's decision:

### **Top Contenders**
*   **Sneha (Top Profit & Margin among high-volume reps):** Sneha generated the highest total profit (**6,996,508.5**) and achieved the second-highest profit margin (**14.31%**) while managing a high volume of orders (865) and units (3,480.0). She also generated the second-highest net revenue (**48,901,393.5**).
*   **Priya (Top Revenue Generator):** Priya tied with Sneha for the highest order volume (865) and generated the highest net revenue (**49,114,230.5**). Her profit stands at **6,859,290.5** with a 13.97% margin.
*   **Karan & Amit (Efficiency Leaders):** While lower in total revenue, Karan (**15.09%**) and Amit (**15.0%**) delivered the highest profit margins in the team, indicating strong pricing control or lower discounting.

---

### **Business Interpretations & Recommendations**

1.  **Reward Sneha if the primary company goal is bottom-line profitability:** Sneha delivered the highest absolute profit while maintaining a strong profit margin and high top-line revenue, making her the most well-rounded high-volume performer.
2.  **Reward Priya if the primary company goal is market share and top-line growth:** Priya brought in the most gross cash (Net Revenue) for the business with the exact same order count as Sneha.
3.  **Consider a Tiered Reward Structure:** Because Sneha and Priya performed exceptionally well across volume, revenue, and profit, management should consider rewarding both—perhaps recognizing **Sneha** for *Profitability Excellence* and **Priya** for *Revenue Generation*. Additionally, a nod to **Karan** for *Margin Efficiency* would acknowledge cost-effective selling.

## Dynamic Business Calculations

In [106]:
def compare_regions(region1, region2):

    r1 = df[df["Region"].str.lower() == region1.lower()]
    r2 = df[df["Region"].str.lower() == region2.lower()]

    revenue1 = r1["Net_Revenue"].sum()
    revenue2 = r2["Net_Revenue"].sum()

    profit1 = r1["Profit"].sum()
    profit2 = r2["Profit"].sum()

    return {
        region1: {
            "Revenue": round(revenue1, 2),
            "Profit": round(profit1, 2)
        },
        region2: {
            "Revenue": round(revenue2, 2),
            "Profit": round(profit2, 2)
        }
    }

Dynamic Product Comparison

In [107]:
def compare_products(product1, product2):

    p1 = df[df["Product"].str.lower() == product1.lower()]
    p2 = df[df["Product"].str.lower() == product2.lower()]

    revenue1 = p1["Net_Revenue"].sum()
    revenue2 = p2["Net_Revenue"].sum()

    profit1 = p1["Profit"].sum()
    profit2 = p2["Profit"].sum()

    units1 = p1["Quantity"].sum()
    units2 = p2["Quantity"].sum()

    return {
        product1: {
            "Revenue": round(revenue1, 2),
            "Profit": round(profit1, 2),
            "Units Sold": int(units1)
        },
        product2: {
            "Revenue": round(revenue2, 2),
            "Profit": round(profit2, 2),
            "Units Sold": int(units2)
        }
    }

In [108]:
compare_products("Laptop", "Smartphone")

{'Laptop': {'Revenue': np.float64(111683693.0),
  'Profit': np.float64(10994103.0),
  'Units Sold': 2428},
 'Smartphone': {'Revenue': np.float64(48437800.0),
  'Profit': np.float64(6329800.0),
  'Units Sold': 1914}}

AI Recommendation Engine

In [109]:
def get_ai_recommendation(question, data):

    prompt = f"""
You are a professional AI Sales Analyst.

User question:
{question}

Verified calculations from Python:
{data}

Provide:

1. Direct answer
2. Key numbers
3. Business interpretation
4. Recommended action

Rules:
- Use only the supplied data.
- Never invent numbers.
- Clearly distinguish facts from recommendations.
- Keep the answer concise and business-focused.
"""

    return ask_gemini(prompt)

In [110]:
comparison = compare_regions("North", "South")

answer = get_ai_recommendation(
    "Which region should management focus on?",
    comparison
)

print(answer)

Based on the verified calculations, here is the sales analysis to guide management's focus:

### 1. Direct Answer
Management should focus on the **North** region, as it outperforms the South in both total revenue and profitability.

### 2. Key Numbers
* **North Region:**
  * Revenue: $88,641,741.50
  * Profit: $12,658,576.50
* **South Region:**
  * Revenue: $69,072,935.00
  * Profit: $10,255,010.00
* **Variance (North vs. South):**
  * Revenue Difference: +$19,568,806.50
  * Profit Difference: +$2,403,566.50

### 3. Business Interpretation
* **Fact:** The North region generates approximately 28.3% more revenue and 23.4% more profit than the South region.
* **Fact:** Both regions are profitable, but the North represents a larger share of the overall business value based on the provided metrics.

### 4. Recommended Action
* **Recommendation:** Allocate additional sales resources, marketing budgets, and high-performing talent to the North region to maximize and scale these higher returns.
* **Recommendation:** Conduct a comparative review of the North region's sales strategies to identify best practices that can potentially be adapted and applied to improve the performance of the South region.

## Final AI Analyst Function

In [111]:
def ai_sales_analyst(question):

    selected_analyses = select_multiple_analyses(question)

    analysis_text = str(selected_analyses)

    prompt = f"""
You are an AI Sales Analyst.

User question:
{question}

Verified business data:
{analysis_text}

Analyze the question using the provided data.

Give:
1. Direct answer
2. Important numbers
3. Business interpretation
4. Practical recommendation

Rules:
- Use only the supplied data.
- Do not invent numbers.
- Be concise.
"""

    return ask_gemini(prompt)

In [112]:
answer = ai_sales_analyst(
    "Which product is most profitable?"
)

print(answer)

**1. Direct Answer**
The most profitable product in terms of absolute net profit is the **Laptop**. However, in terms of efficiency (profit margin), the **Notebook** is the most profitable.

**2. Important Numbers**
*   **Laptop (Highest Absolute Profit):**
    *   Profit: $10,994,103.00
    *   Net Revenue: $111,683,693.00
    *   Profit Margin: 9.84%
*   **Notebook (Highest Profit Margin):**
    *   Profit Margin: 80.01%
    *   Profit: $536,147.00
    *   Net Revenue: $670,112.00
*   **Other Top Absolute Profit Contributors:**
    *   Smartphone: $6,329,800.00 profit (13.07% margin)
    *   Office Chair: $4,775,600.00 profit (21.69% margin)

**3. Business Interpretation**
*   **Volume vs. Margin:** Laptops drive the bulk of the company's bottom line through high-volume, high-value sales, despite having a relatively low profit margin (9.84%).
*   Conversely, items like **Notebooks** (80.01% margin), **Pen Sets** (64.83% margin), and **Keyboards** (37.53% margin) yield exceptional margins but generate much lower total profit due to smaller net revenues.

**4. Practical Recommendation**
*   **Protect Core Revenue:** Continue prioritizing the sales and marketing of Laptops and Smartphones, as they are the primary drivers of total monetary profit.
*   **Cross-Sell High-Margin Items:** Leverage high-margin accessories (like Keyboards and Notebooks) as add-on purchases during Laptop or Office Chair transactions to maximize basket size and overall profitability without significantly increasing costs.